### ISSUE TITLE
issue with getRandomImages and unpublished albums

### ISSUE THREAD

**Issue by vincent3569** [zenphoto/zenphoto#882] opened 2015-01-04 19:57 UTC
hi
when an album is unpublished (or published with a "Publish date" in the future) and it have some published pictures, they can be returned by getRandomImages().
according to me, this function should not return an unpublished picture (it's ok) and an published picture in a unpublished album.

I wish to the team an happy new year.
may you have a lot of funny projects.

**Comment by gjr-osweb** [comment] 2015-01-04 20:45
Hi Vincent,

I am trying to reproduce your issue.  If you are logged in, published images in an unpublished album will be returned by the random image function.  If you are logged out, they are not returned. Are you requesting that these images not be returned even if logged in, because that would go against the way publish/unpublish works with logged in admins.  Please clarify if you can in case I am missing something.

Thanks

**Comment by vincent3569** [comment] 2015-01-04 20:49
of course myy request is about not logged users.
this is the issue : if you are logged in, published images in an unpublished album are returned by the random image function.

**Comment by gjr-osweb** [comment] 2015-01-04 20:56
Sorry, what you are saying above is not an issue, it is the way it works.

**Comment by vincent3569** [comment] 2015-01-04 21:42
maybe, I had this discussion with Stephen in the past...
in one hand, when you navigate through the gallery, if you have an unpublished album, you can't access to it and you can't see pictures whereas they are published or not.
in other hand, when you use getRandomImages, if you have an unpublished album, you can see published pictures.
according to me the rights on albums are most important that rights on picture in this album whatever the template function used to access to pictures.
unpublised album should mean all pictures are unpublished.
the actual behaviour is not relevant.

**Comment by gjr-osweb** [comment] 2015-01-04 21:59
I cannot reproduce your issue. Maybe others can. Logged off users cannot see published images in an unpublished album from the random functions.

**Comment by fretzl** [comment] 2015-01-05 10:43
I cannot reproduce it either.

**Comment by vincent3569** [comment] 2015-01-05 12:06
so...
I have some tests with my test site:
* 1st test: I have 2 albums:
- a published one, with only unpublished pictures
- a unpublished one, with only published pictures
I can't reproduce myself the issue. in 2 cases, there are no picture returned by getRandomImages (maybe a cache issue on my personnal computer?)

* I have another test with 3 albums:
- a published one, with only unpublished pictures
- a unpublished one, with only published pictures
- a published one (but with a "Publish date" in the future), with only published pictures
in that case, I have pictures of no yet published album returned by getRandomImages

=> getRandomImages should not return published pictures of an published album with a a "Publish date" in the future.
fyi, getImagesStatistic works fine (it does not return published pictures of an published album with a a "Publish date" in the future)
as far I can see, it uses the getAllAccessibleAlbums() function (which gets an array of the album ids of all accessible albums)

**Comment by acrylian** [comment] 2015-01-05 12:16
First Happy New Year, Vincent. I can reproduce the issue. The random image functions indeed do not care for the future publish date. They do check access but apparently not this.

**Comment by vincent3569** [comment] 2015-01-05 12:21
in the same way:
in admin/news (and pages), they are 3 states: Published/Not published/Scheduled for publishing.
with that, you can see scheduled news and pages and you can publish immediately (by skipping scheduling).
this behavior does not exist for albums and pictures (the 3 states for pictures could appear on image order tab).

maybe needs another ticket about that behavior...

**Comment by acrylian** [comment] 2015-01-05 12:36
> this behavior does not exist for albums and pictures (the 3 states for pictures could appear on image order tab).
I believe that is already on our list.

**Comment by vincent3569** [comment] 2015-01-05 13:23
what is the date for this major release ?
since 1.4.6 there is no minor bug fix release ...

**Comment by acrylian** [comment] 2015-01-05 13:40
Bug fix release soon and no date for the major release yet, sorry.

**Comment by acrylian** [comment] 2015-01-26 13:30
This should be fixed.

**Closed by acrylian** 2015-01-26 13:30 UTC
Labels: bug
