### ISSUE TITLE
When upgrading Zenphoto to 1.6 Imagick image option changed to GDlibrary

### ISSUE THREAD

**Issue by JesseHC** [zenphoto/zenphoto#1358] opened 2022-12-15 10:08 UTC
When upgrading from Zenphoto 1.5.9 to 1.6 the image option for graphics library was changed from Imagick to GDlibrary. This happened on both my local test server running on MAMP and my live server, which is strange, since both kept all of my other options.

This might be minor for most users, but can have repercussions depending on your image types, if not caught.

**Comment by acrylian** [comment] 2022-12-15 10:21
Please review your setup log. The general option has been renamed. and the interface changed but we actually do check if imagick was enabled previously and also if it actually is available on setup setting default options:

     if(getOption('use_imagick') && $_zp_graphics->imagick_present) {
	   setOptionDefault('graphicslib_selected', 'imagick', true);
     } else {
	  setOptionDefault('graphicslib_selected', 'gd', true);
     }
     purgeOption('use_imagick');

**Comment by JesseHC** [comment] 2022-12-15 10:28
This is what both servers said with no errors about it.

Test server setup log-
`Pass: Graphics support:PHP GD library bundled (2.1.0 compatible) [available]PHP Imagick library 3.4.4ImageMagick 6.9.6-2 Q16 x86_64 2020-11-30 http://www.imagemagick.org [enabled]`

Live server setup log-
`Pass: Graphics support:PHP GD library bundled (2.1.0 compatible) [available]PHP Imagick library 3.4.3ImageMagick 6.7.6-8 2016-07-19 Q16 http://www.imagemagick.org [enabled]`

**Comment by acrylian** [comment] 2022-12-15 10:52
Then I have no idea right now why it didn't keep the option… But I think for most sites it will not make any real difference since both libs support generally the same image formats nowadays respectively we do. It always comes down to jpg or png I assume. webp might catch up and I would see no apparent reason to us gif if png is superior…

**Comment by JesseHC** [comment] 2022-12-15 10:56
Could it be the `purgeOption('use_imagick');` at the end? I'm not a programmer, just asking.

**Comment by acrylian** [comment] 2022-12-15 10:58
Actually no as that just removes the old now unused option after the new  'graphicslib_selected' was set.

**Comment by MarkRH** [comment] 2022-12-15 22:36
My local upgrade also unchecked the option to use Imagick but it was still aware it existed and I was able to re-select it... I figured it might have been due to going from 1.5.7 to 1.6.

**Comment by acrylian** [comment] 2022-12-16 08:56
Okay, thanks, that makes two. I did upgrade several site but I didn't pay atention as some don't even have Imagick and it also does not matter in these cases. 

We will check what fails here, perhaps the check fir imagick being present. In any case I realize that our code tries to cover the old option but of course might reset the new one on further updates, too.

**Comment by acrylian** [comment] 2022-12-16 09:47
> I realize that our code tries to cover the old option but of course might reset the new one on further updates, too.

Well, actually no, since we are setting defaults here. Anyway, I will try to fix this behaviour.

**Comment by acrylian** [comment] 2023-04-02 11:45
I could not reproduce it. Since this is a one time issue upgrading to 1.6 and the option can be changed I will close this for now.

**Closed by acrylian** 2023-04-02 11:45 UTC
Labels: bug, works for me
