### ISSUE TITLE
Image generator fails with filenames containing 'x00'

### ISSUE THREAD

**Issue by sam-19** [zenphoto/zenphoto#1305] opened 2021-07-23 07:12 UTC
I noticed a strange thing about the image generator today, when I uploaded some pictures of a red fox to my gallery. My usual naming scheme for files is a descriptive name followed by a three-digit running number, in this case RedFox001, RedFox002 etc. After uploading, the image generator failed to display any of the images. Adding `&debug` to the image processor link for my second red fox picture gave this error:

**Zenphoto Image Processing Error: Image not found; file RedFo2.jpg does not exist.**

So, apparently the image processor is parsing the `x00` in `RedFox002.jpg` as the null character `\x00` instead of a literal string. Original image file links work and can be accessed, just none of the modified (thumbnail) image links work. I didn't test if the same applies to other character codes except `\x00`.

The obvious solution is to rename the files to something like `RedFox_001.jpg`, but I have a feeling someone else will eventually run into this problem too.

My Zenphoto version is 1.5.9.

Edit: Renaming the files on the filesystem and in the database fixed the issue.

**Comment by fretzl** [comment] 2021-07-23 08:23
I can confirm this happening only with `x00` sequence in the file/folder name.

**Comment by acrylian** [comment] 2021-07-23 10:32
I can also confirm it. 

> The obvious solution is to rename the files to something like RedFox_001.jpg, but I have a feeling someone else will eventually run into this problem too.

Yes, indeed, that may also cause the number to be mistaken as the general size (without cropping and such in cachefile names . RedFox_100.jpg  would be an undropped image with the size of 100px (width or height, depending on which side to use is set on te options) We had that issue reported but choose not to fix it as it would invalidate a lot of cache files on larger sites.

**Comment by acrylian** [comment] 2021-07-23 13:31
There is a fix on Github now. Note that is 1.6a and work in progress different from 1.5.9 already so should not be installed on production sites right now. You could apply the fix manually to test if you like by looking at the reference above.

**Comment by sbillard** [comment] 2021-07-31 18:29
Just so you know, The problem was a typo in the original code. "x00" should have been written "\x00". The first is a string with the letter x and two zeros. The second is the escape code for the null character.

**Comment by acrylian** [comment] 2021-07-31 18:37
Thanks, makes sense…

**Comment by sbillard** [comment] 2021-07-31 19:23
`$filename = preg_replace(array('/[[:cntrl:]]/', '/\/\/+/', '/\/\.\./', '/\/\./', '/:/', '/</', '/>/', '/\?/', '/\*/', '/\"/', '/\|/', '/\/+$/', '/^\/+/'), '', $filename);` is actually a better fix. This removes all ASCI control characters.

**Comment by acrylian** [comment] 2021-08-01 07:30
Thanks, that's indeed more universal.

**Comment by acrylian** [comment] 2021-08-20 17:37
Fixed in the support build.

**Closed by acrylian** 2021-08-20 17:37 UTC
Labels: bug
