### ISSUE TITLE
1.6 behavior in Albums with subAlbums

### ISSUE THREAD

**Issue by FilippoBoscarino** [zenphoto/zenphoto#1375] opened 2023-02-26 14:18 UTC
There is a strange behaviour introduced in this version, related to the subject.
If in one Album you got SubAlbums and Images, themes like garland (just to cite a theme included wich tries to show both in the same page in thumb templates) and others, they show all the albums, but only the first image of the main Album.
No issues noticed with albums with only Images in or in the 2nd page and more of the ones with SubAlbums.

**Comment by acrylian** [comment] 2023-02-26 15:29
the transition handling has changed in 1.6. Please see here https://www.zenphoto.org/news/zenphoto-1.6/#--general-changes-and-fixes Also review the related theme options.

**Comment by FilippoBoscarino** [comment] 2023-02-26 16:10
Yes, I am aware of the lack in support for old themes, and I cited garland only to describe a well know behaviour.
Personally I use a custom theme I build by myself, starting from Paradigm theme.
My problem is right now due to the fact I did not find any theme without this issue, showing the solution to be migrated to my own theme.
Also the lack of a reference for 1.6.x version in doc.zenphoto.org it an obstacle to easily understand which is the intended way to browse and navigate the Album dependancies from now and forward in future versions.
I am just trying to discover it debugging by point-of-injections in the code, and it is very frustrating, also because i really don't know if it will be just a bug fix or a future-proof upgrade of my code

**Comment by FilippoBoscarino** [comment] 2023-02-26 16:23
What I discovered is that there is a unexpected behaviout of the non-deprecated function next_image(), used in the while list used to build up the thumbs page.
With the boolean param TRUE, returns the correct whole list of the thumbs, but overriding pagination as due.
If you use param FALSE, returns unexpected result false, after the first image's thumb.
IMHO this seems to be a bug of the function.

**Comment by acrylian** [comment] 2023-02-26 16:23
The transition change is actually theme independent. Any theme that uses the standard next_album/image loops  with pagination should work with that generally as it is an internal calculation. The transition stuff was really unpredictable in results the former way (and no one including us really understood the options…) and is much more with the new way because you can now set the number exactly what is shared. It still is a bit abstract. I would generally recommend not to use albums that contain images and albums at the same time as it in generally provides a "better" structure/organisation (which is what I do on basically all sites I do with ZP) or just not use a transition page at all.

> Also the lack of a reference for 1.6.x version in doc.zenphoto.org 

We had to switch our doc generator because of PHP 8+ and sadly its result is not GDPR compliant at the moment. We are working on fixing that which is not that simple with a readymade solution (and some lack of time generally). There are generally a few functions and methods named `getFirstPageImages()`

**Comment by acrylian** [comment] 2023-02-26 16:24
Yes, the true parameter of course disables pagination and therefore also any transition page behaviour. You really need to experiment with the transition page options and as said it is not really an exact thing since the result still depends a bit.

**Comment by FilippoBoscarino** [comment] 2023-02-26 16:28
Thanks for your prompt reply, also if the solution is far from being addressed in my mind...

**Comment by FilippoBoscarino** [comment] 2023-02-27 14:37
Update: I have fixed my issue bypassing the internal while loop based on next_image() in my template, recostructing a new one by myself, and now my template works either on first and following pages.
I did not modify the next_album() loop, that looks like working fine.
I am at disposal to suggest the solution to whom it may concerns.

But now a new issue rised up.
For example, an Album with 1 subAlbum and 226 pics, paged 40pics per page, should be showed in 6 pages: first with 1 subAlbum and 40 images, following with 40 imapes each and the 6th pages with only 26 images.
This is now showed correctly, but getPageNavList() calculates 7 pages, and 7th page is showed reasonably empty.

Assuming you won't follow up 1.6 version as declared, I am wondering if you have to plan a deep and well stressed testing session on album/images loop on 2.x, because I am afraid that this issue can be verified also in the future if not re-engineered the whole process.
Cheers

**Comment by acrylian** [comment] 2023-02-27 15:03
> But now a new issue rised up.

**Comment by acrylian** [comment] 2023-02-27 15:07
(In case you read via mail, I accidentally hit enter to soon on the above one). We really tested this feature. If you tell me that the above recommendation does not work as expected we will try to reproduce that and if fix it. That would be considered a bug and those we of course fix in 1.6+

**Comment by FilippoBoscarino** [comment] 2023-02-27 16:03
> Not sure if you are referring to your own custom solution or the original one. Generally you should be able to get 40 images on the first page by setting both options to the same value.<

I think I have finally addressed the point.

In the earlier versions and since the beginning, I could obtain my desired effect of having 1 SubAlbum and 40 Images in the 1st Album page, also by this option configuration
![image](https://user-images.githubusercontent.com/126400084/221608950-098c098d-073b-4f74-be60-0cad370d9491.png)
Now I obtain the same desired result only by this one
![image](https://user-images.githubusercontent.com/126400084/221612982-57c2e5b5-0362-44f8-805a-cc78ab036888.png)
I assume the bug was in the earlier versions and that caused me not to really understand the exact meaning of this option.
Maybe a foggy translation has contributed ;)

Rolling back to original cycle, now works fine.
Sorry for misunderstanding.
I think that this issue can be considered solved.

Many thanks for your patience :)

**Comment by acrylian** [comment] 2023-02-27 16:43
Thanks for the follow up! That's how it should work in your case. No problem a double check never hurts and Zenphoto   has a lot options and functionality. Glad you didn't discover any new bugs ;-) 

I will close this then!

**Closed by acrylian** 2023-02-27 16:43 UTC
