### ISSUE TITLE
Site copyright URL not saving under Options - Gallery in both 1.5.9 and the 1.6a support build

### ISSUE THREAD

**Issue by JesseHC** [zenphoto/zenphoto#1320] opened 2022-02-19 10:58 UTC
The value for **_Site copyright URL_** under _Options - Gallery_ will not apply. It always stays empty.

The **_Image Copyright URL_** value under _Options-Image_ does save, but it does not display on the image pages, if that is where it is supposed to show.

I’ve tried this in 1.5.9 and with the latest 1.6a support build.

Also, the drop-down option for the Gallery Site copyright URL and Image Copyright URL is only “Custom”, so maybe that can be removed if there is no other options?

Not sure if the printCopyrightNotice in line 22 of inc-footer.php is supposed to show the Gallery Site copyright URL or the Image Copyright URL? I’m confused by that. Either way, it is not displaying.

Thanks.

**Comment by JesseHC** [comment] 2022-02-19 11:02
Not sure if it is related, but on my live server with 1.5.9 I’ve been getting lots of errors for months in the debug logs-

> {578433:Sun, 30 Jan 2022 07:19:10 GMT}
> NOTICE: Undefined variable: notice in /home/zenphoto/zp-core/class-image.php on line 956
> Image->getCopyrightNotice called from htmlmetatags::getHTMLMetaData (html_meta_tags.php [286])
> from zp_apply_filter (functions-filter.php [150])
> from include (image.php [11])
> from include (index.php [130])
> from index.php [56]
> {578433:Sun, 30 Jan 2022 07:19:10 GMT}
> NOTICE: Undefined variable: notice in /home/zenphoto/zp-core/class-image.php on line 959
> Image->getCopyrightNotice called from htmlmetatags::getHTMLMetaData (html_meta_tags.php [286])
> from zp_apply_filter (functions-filter.php [150])
> from include (image.php [11])
> from include (index.php [130])
> from index.php [56] 

I haven’t seen it on my 1.6a test server, but I also haven’t browsed most image pages on there.


On image pages in both 1.5.9 and 1.6a, under “Image Info” both entries displaying same info (“© [date] [name], all rights reserved”)-

Copyright Holder:
Copyright Notice:

For holder, it should be the name of the person, and notice should be the notice.

**Comment by acrylian** [comment] 2022-02-19 11:46
> Also, the drop-down option for the Gallery Site copyright URL and Image Copyright URL is only “Custom”, so maybe that can be removed if there is no other options?

If you want to enter your own url you must select "custom" in the selector. We focus primarily on Zenpage pages which is while this is aimed at this. So "custom" means your own url.

> Not sure if the printCopyrightNotice in line 22 of inc-footer.php is supposed to show the Gallery Site copyright URL or the Image Copyright URL? I’m confused by that. Either way, it is not displaying.

The footer is not related to the image or whatever single page you are displaying so it is meant to use the gallery copyright. This is working for me in the basic theme as intended. But the link indeed is missing, be it Zenpage page or not. I will look into that.

> On image pages in both 1.5.9 and 1.6a, under “Image Info” both entries displaying same info (“© [date] [name], all rights reserved”)-

The image copyright holder is as mentioned used for html meta data, not for image metadata (EXIF/IPTC). These are the values embedded in the image its self. However the copyright notice is used for sized images in metadata if applicable (so jpegs only).

The image copyright notice is not used in themes right now and there is actually no template function for these right now. These are available as image class methods and can be used for example via the `$_zp_current_image` object currently.  You have to add these yourself if you like to display them. I will see to add a `printImageCopyrightNotice()` equivalent to the existing `printCopyrightNotice()` for the site in general.

**Comment by acrylian** [comment] 2022-02-19 11:50
I can confirm that the links is not used in `printCopyrightNotice()`. Perhaps intentionaly or an oversight or it was intention so you can create your own link. Which you can easily using `printLinkHTML()`. But it makes sense to have at least a parameter for a link for convenience.

**Comment by acrylian** [comment] 2022-02-19 11:53
Additionally I will setup themes to use the image copyright notice if set. But not for meta data as this is basically meant as an addition or replacement if the image has nothing embeeded.

**Comment by acrylian** [comment] 2022-02-19 12:14
> Not sure if the printCopyrightNotice in line 22 of inc-footer.php is supposed to show the Gallery Site copyright URL or the Image Copyright URL? I’m confused by that. Either way, it is not displaying.

Additional comment: It is rather confusingly placed as I realized but you have to enable the display on the theme options. For some reasons I don't remember we added that there and not where the other options are… Will move that one so all are together as they probably should in the first place.

**Comment by acrylian** [comment] 2022-02-28 10:54
This is meanwhile fixed in the support build 1.6a

**Closed by acrylian** 2022-02-28 10:54 UTC
Labels: bug, enhancement
