### ISSUE TITLE
Video thumbnails cropped and stretched even when cropping is turned off

### ISSUE THREAD

**Issue by JatB** [zenphoto/zenphoto#1132] opened 2018-02-14 10:58 UTC
If you have cropping turned off, Zenphoto still crops video thumbnails, but will then stretch them out in the theme. So you end up with cropped and warped thumbnails.

Here I have a 1920x1080 .jpg labeled "1920x1080 Image only" and a .jpg with the same resolution labeled "1920x1080 Video thumbnail" alongside a .mp4 video with the same name-
![image only thumbnail and video thumbnail](https://user-images.githubusercontent.com/10157440/36199706-3887cde8-112f-11e8-9dd1-c2c4ce641ed7.png)

It is easy to test for-
- Turn off cropping in your theme options.
- Add a video thumbnail image alongside your video (it helps if the video image is 16:9 to easily see the crop)
- The thumbnail for the video that will be displayed in the theme will have both the left and right sides cropped and then stretched.

For example, in my theme options I currently have thumb size set to 200 pixels and crop thumbnails turned off. This is on a slightly modified version of the Basic theme, so you can test it on there.

![admin - options - theme](https://user-images.githubusercontent.com/10157440/36199830-98527c14-112f-11e8-97b6-0739be6270f8.png)

Both resulting image thumbnails will be set to width="200" height="113" _BUT_ the video thumbnail will be square cropped in the middle at 200x200 with “_w100_h100” added to the filename.

For example, the image only thumbnail-
src=“/demosite/cache/video_thumbnail_test/video_thumbnail_test-image_only_200_thumb.jpg"
![video_thumbnail_test-image_only_200_thumb](https://user-images.githubusercontent.com/10157440/36200486-b7de66a4-1131-11e8-969e-a1fdd1302c61.jpg)

The video thumbnail-
src=“/demosite/cache/video_thumbnail_test/video_thumbnail_test_200_w100_h100_thumb.jpg"
![video_thumbnail_test_200_w100_h100_thumb](https://user-images.githubusercontent.com/10157440/36200497-c0ac1fc4-1131-11e8-8bfa-d6160342bd9d.jpg)

What it should look like-
![video_thumbnail_test-what_it_should_look_like_200_thumb](https://user-images.githubusercontent.com/10157440/36200532-dda0f6c2-1131-11e8-997d-d28444c06129.jpg)

What’s interesting is that the video player will still display the correct full-sized video thumbnail for the poster (tested in both jplayer and mediaelementjs_player)

This has annoyed me for years, so I’m finally submitting a bug report for it.

I’ve seen other people complain about the issue, but it was never resolved-
http://forum.zenphoto.org/discussion/2749/video-thumbnails
http://forum.zenphoto.org/discussion/1014069/video-thumbnails-distorting
http://forum.zenphoto.org/discussion/10019/best-method-for-custom-thumbnail-sizes
http://forum.zenphoto.org/discussion/4346/using-printcustomsizedimagemaxspace-for-video-thumbs

Thanks, and let me know if you want the sample images and video file I whipped up to test for yourselves.

**Comment by acrylian** [comment] 2018-02-14 11:25
Thanks, could you please try the support build? I mean we worked on this some time ago but don't remember anymore. Just to note the video thumbs do not use the default image settings at all but custom one because of the player size.

**Comment by JatB** [comment] 2018-02-14 11:58
It will take me some time to setup a test server to try out the support build, so I will have to get back to you on that.

I’m not sure why the video thumbs do not use the default image settings, because the media players do not appear to be pulling the generated thumbnail, but rather the full-sized video image for the poster image.

For example, using mediaelementjs_player I get-

<video id="mediaelementjsplayer19853" class="mep_player" width="100%" height="509" controls="controls" preload="none" poster=“/demosite/cache/video_thumbnail_test/video_thumbnail_test_w1920_h1080_cw1920_ch1080_thumb.jpg" style="max-width: 100%">

It is using the full-sized 1920x1080 image, not the smaller 200x200 cropped thumbnail, adding “_w1920_h1080_cw1920_ch1080_thumb” to the filename.

I do have the Quicktime width and height set to 1920x1080 under options for class-video and the same for poster width and height under options for mediaelementjs_player, but the defaults for both I believe were higher than the cropped thumbnail’s 200x200 anyways.

**Comment by acrylian** [comment] 2018-02-14 12:11
As you can see the mediaelement player (which is not fully official yet) does get a custom size. It generally tries to get a cover for the defautl 16:9 video size. Besides that it may very well be that the player or the html5 spec does some resizing here. Cropping and resizing is a bit tricky since the internal function do take the actual size of the image to be processed into account.

The quicktime settings are not important (and are obsolete anyway).

**Comment by acrylian** [comment] 2018-02-14 12:23
Addition: Sorry, we generally call image for videos "video thumbs" (newer and better term is actually "sidecar image"). I meant the image on the video player itself and confused myself. The thumbs on the overview pages of course use the default settings for all images (unless a theme does choose to use custom sizes).

**Comment by JatB** [comment] 2018-02-15 14:25
After a bit of work, I was able to get the current support build running on a test server. The issue still exists there.

On a fresh install with everything set to default (thumbnails at 100 pixels, with cropping on), it looked like this-

![zenphoto support build - default - cropping on](https://user-images.githubusercontent.com/10157440/36260981-c603ef10-1217-11e8-9907-cb4f9758f21b.png)

What’s interesting to note is that for only the image, it is cropping on the right side, but for the video sidecar image it is cropping on the left and right.

With cropping turned off, but still at the default of 100 pixels, you get this-

![zenphoto support build - cropping off](https://user-images.githubusercontent.com/10157440/36260986-cc23e2e2-1217-11e8-96ae-39710a751c4f.png)

By default jplayer is pulling and shrinking the video sidecar image correctly for the poster image-

![jplayer pulling the correct sidecar image for poster](https://user-images.githubusercontent.com/10157440/36261020-e2dbda08-1217-11e8-84ef-5ca18d32dc76.png)

**Comment by JatB** [comment] 2018-02-15 14:29
A bit off topic, but I wasn’t able to get the current support build to do a fresh install. It wouldn’t work until I installed the current version of 1.4.14, copied the working version of zenphoto.cfg.php into the support build’s zp-data folder and then ran the setup again.

It wouldn’t display any visual error messages, but I did pull these from the error logs (that’s how I figured out to try to copy the file over). Maybe this is a known thing, but I wanted to let you know.

_zp-data/debug.log would give me this over and over-_

{6228:Thu, 15 Feb 2018 12:09:03 GMT}
  WARNING: fileperms(): stat failed for /Applications/MAMP/htdocs/zenphototest/zp-data/zenphoto.cfg.php in /Applications/MAMP/htdocs/zenphototest/zp-core/functions-basic.php on line 147
  fileperms called from require_once (functions-basic.php [147])
    from require_once (admin-globals.php [12])
      from setup.php [2]


_php_error.log would give me this over and over-_

[15-Feb-2018 13:09:03 Europe/Berlin] PHP Warning:  file_get_contents(/Applications/MAMP/htdocs/zenphototest/zp-data/zenphoto.cfg.php): failed to open stream: No such file or directory in /Applications/MAMP/htdocs/zenphototest/zp-core/functions-basic.php on line 115
[15-Feb-2018 13:09:03 Europe/Berlin] PHP Notice:  Undefined index: mysql_prefix in /Applications/MAMP/htdocs/zenphototest/zp-core/functions-basic.php on line 120
[15-Feb-2018 13:09:03 Europe/Berlin] PHP Warning:  fileperms(): stat failed for /Applications/MAMP/htdocs/zenphototest/zp-data/zenphoto.cfg.php in /Applications/MAMP/htdocs/zenphototest/zp-core/functions-basic.php on line 147
[15-Feb-2018 13:09:03 Europe/Berlin] PHP Fatal error:  Call to undefined function db_quote() in /Applications/MAMP/htdocs/zenphototest/zp-core/functions.php on line 1961

**Comment by acrylian** [comment] 2018-02-15 14:39
We will take a look at the video thumb issue once we find the time. Generally these sidecar images are outside the normal images and not stored in the database itself.

*Shortly to your install issues: Sounds like a permissions issues but there should be no real differences regarding setup at all…  We will try to reproduce this. For the future please generally don't mix different topics, better open a new ticket. If more discussion is needed, it should happen on its own ticket.*

**Comment by acrylian** [comment] 2018-02-21 18:54
Please try the support build again(also the setup issue).

**Comment by JatB** [comment] 2018-02-22 16:12
Thanks! That did it!

I tested it with cropping on (default), cropping off, and cropping off with a custom size (using both GD and Imagick).

![video_thumbnail_test now working](https://user-images.githubusercontent.com/10157440/36547628-2a596d1a-17a3-11e8-87df-1e43b5c76d50.png)

![video_thumbnail_test now working - custom size](https://user-images.githubusercontent.com/10157440/36547649-36724414-17a3-11e8-8792-9f51dd0428e9.png)

I also didn’t have any issues with the install this time.

The only thing I would like to mention, since we are on the topic, is that for some reason the default crop is slightly off.

![video_thumbnail_test - default cropping](https://user-images.githubusercontent.com/10157440/36549118-d6bf5f6c-17a6-11e8-91e3-5b56e424c618.png)

![options - theme -default crop](https://user-images.githubusercontent.com/10157440/36549140-df8ebfa2-17a6-11e8-8fb1-061ca0011355.png)

It does not crop from the center, or do it strictly from the left or right sides. For some reason it inserts a slight margin on the left side, then does it from there when it does the crop.

Here’s the same images shrunk to 100 pixels on the shortest side in Photoshop and then cropped to the center at 100 pixels on the longest side.

![video_thumbnail_test-image_only - cropped in photoshop](https://user-images.githubusercontent.com/10157440/36549177-f61128dc-17a6-11e8-8062-6098fc400c75.png)

![video_thumbnail_test - cropped in photoshop](https://user-images.githubusercontent.com/10157440/36549182-f92d5446-17a6-11e8-9f8c-889c090af824.png)

Not the end of the world by any means, just wanted you to be aware of it.

Thanks for all your help and hard work!

**Comment by acrylian** [comment] 2018-02-22 16:27
Thanks for the feedback. I see what you mean with the offset as well. Somehow it never bothered me at all being less obvious on "real images". But we'll try to look at this.

**Comment by acrylian** [comment] 2018-08-29 19:55
I'll close this as the actual issue is fixed. We keep the center/non center cropping in mind as we are working on related stuff anyway and hopefully this will perhaps be covered, too.

**Closed by acrylian** 2018-08-29 19:55 UTC
Labels: under investigation
