### ISSUE TITLE
HTTP Accept-Language not working properly

### ISSUE THREAD

**Issue by kochs-online** [zenphoto/zenphoto#1207] opened 2019-02-17 02:08 UTC
#1164 made me play around with the language options. I noticed that chosing the radio button for "HTTP_Accept_Language" option does not work properly for me. I have allowed (ticked the checkbox for) Dutch, English (US), French and Italian, i.e. all the up-to-date language packs. NB: German is not enabled.

My browser (Firefox 65.0) is sending this as part of the HTTP request header:
`Accept-Language: de-DE,de;q=0.8,en-US;q=0.5,en;q=0.3`

So I'd expect Zenphoto to use English as my prefered language, but the setup will be in Dutch.

Switching the radio button from "HTTP_Accept_Language" to "English (US)" and enabling the checkbox for "German" will render the backend in German although I would not expect Zenphoto to respect the Accept-Language header field in this case.

**Comment by acrylian** [comment] 2019-02-17 12:34
I never noticed this. Generally proper language switching requires the server to support that locale. So without Dutch locale no Dutch language.

Also check you can set the preferred language on the user account. If that is set to German it will override the general language option (if the above applies).

**Comment by kochs-online** [comment] 2019-02-17 13:08
> Generally proper language switching requires the server to support that locale. So without Dutch locale no Dutch language, no matte of the http accept setting of the browser.

Yes, of course. But neither the backend language was set to Dutch nor the user's preferred language nor was it part of the HTTP Accept-Language. So it really shouldn't be used during setup, should it?

> Also check you can set the preferred language on the user account. If that is set to German it will override the general language option (if the above applies).

Indeed. German was set as preferred language for my user. That explains the second behaviour I described. (The setup issue is still unsolved.)

**Comment by acrylian** [comment] 2019-02-17 13:46
> So it really shouldn't be used during setup, should it?

No, probably not. Not sure how this can happen. Would need to be able to reproduce this as I never encountered this. Of course I generally do use ZP in English but try German regulary, too.

**Comment by fretzl** [comment] 2019-02-18 10:54
So far I have not been able to reproduce any of this.

**Comment by thany** [comment] 2019-02-26 23:37
Almost the same problems I'm having. I got (after I killed it by restoring a backup that is...) Dutch language no matter what I select for the user or for everyone. I wouldn't go into any other language. Extremely easy to reproduce: just install a fresh zenphoto. Boom.

> I never noticed this. Generally proper language switching requires the server to support that locale.

Absolutely not. Locale is not language. Language is language. Locale is number & date formatting.

**Comment by acrylian** [comment] 2019-02-27 09:24
> Absolutely not. Locale is not language. Language is language. Locale is number & date formatting.

Nope, gettext requires the locale being installed to switch translations. No German, no German languages. Simple as that.

**Comment by kochs-online** [comment] 2019-02-27 11:35
> Generally proper language switching requires the server to support that locale. So without Dutch locale no Dutch language, no matte of the http accept setting of the browser.
> 
> Also check you can set the preferred language on the user account. If that is set to German it will override the general language option (if the above applies).

Coming back to the settings, I find them a bit irritating. Currently there are 4 different sets of options:
1. Enable/disable language pack
2. Enable/disable HTTP Accept-Language
3. Set default (?) language
4. Set user language

And while I can see that all of the options make sense, it's obvious that this can confusing and even conflicting. Maybe this should be improved as well (apart from fixing the problem/solving this issue)?

**Comment by acrylian** [comment] 2019-02-27 11:45
This cannot be made simpler as all are needed:

1. Enable/disable language pack -> You enable the languages you want to use in multilingual environment
2. Enable/disable HTTP Accept-Language -> Let the visitor's browser choose (if possible)
3. Set default (?) language -> Default language if none is requested by the user
4. Set user language -> Preferred language of logged in users

> (apart from fixing the problem/solving this issue)?

We would need to be able to reproduce which we can't so far.

**Comment by thany** [comment] 2019-02-27 12:05
> Nope, gettext requires the locale being installed to switch translations. No German, no German languages. Simple as that. We are not talking about the locales in /zp-core/locales, we are talking about locales installed on the server natively.

Sorry to ruin your technical explanation, but I don't care about gettext. I care about what I'm seeing as a result. My locale is Dutch, and my language is English. Locale and language have *absolutely nothing* to do with each other.

**Comment by acrylian** [comment] 2019-02-27 12:34
> Sorry to ruin your technical explanation, but I don't care about gettext. 

I don't care if you care about gettext. We are trying to find out why you get this and we cannot reproduce it. Since all depends on locale and gettext it is important. Period.

**Comment by thany** [comment] 2019-02-28 22:28
Well then that's another bug to fix: detach locale from language.

As for the bug at hand: maybe there's some stubborn serverside cache that doesn't clear translated texts after switching language. But also: it should be looking at Accept-Language for display language at all. It's way too unreliable, and in some cases, very undesirable. Just pick a default language, like English, and allow the admin to change it to whatever he likes.

It's a simple solution (i.e. remove the bit that tries to be smart) and in many cases a simpler solution is a better one.

**Comment by acrylian** [comment] 2019-03-01 09:11
> Well then that's another bug to fix: detach locale from language.

This does not lead anywhere. We did explain why this is not possible because of coure PHP functionality. If we do that translations will not work as you could select e.g. Dutch but would not get it because it requires the locale. I will not discuss this any further.

**Comment by thany** [comment] 2019-03-01 12:59
Me neither, but midn you, I might open another bug about this in the future. It is absolutely positively possible in PHP. It's absolutely IMpossible using the framework you've chosen to use. But as you will not discuss this any further, we can only hope that this might possibly get fixed in zenphoto 3.0.

**Comment by acrylian** [comment] 2019-03-01 13:25
> It's absolutely IMpossible using the framework you've chosen to use. But as you will not discuss this any further, we can only hope that this might possibly get fixed in zenphoto 3.0

Sorry to disappoint you this will not be "fixed".

**Comment by kochs-online** [comment] 2019-03-01 14:54
> It is absolutely positively possible in PHP.

Just out of curiosity: Can you provide a simple example on how to use `gettext()` without `setlocale()`?

**Comment by acrylian** [comment] 2019-03-01 15:47
I guess he referred to not using gettext at all (which is not an option) but other workarounds of translation like using arrays with the text strings or such.

**Comment by sbillard** [comment] 2019-03-01 17:23
Or using a gettext replacement library. That is what netPhotoGraphics does (since I could never get WAMP to do locale/native gettext correctly.) But for that to work the server PHP has to disable the PHP gettext extension.

**Comment by thany** [comment] 2019-03-04 10:04
I think we're getting off track here.
I am indeed talking about not using gettext, because it incorrectly assumes and requires locale==language.

Since replacing gettext by something slightly more proper is not an option, at least for the moment perhaps, this issue seems to become stale.

In the end, this means that it's currently not possible to have, say, Dutch locale with an English display language. Or any other combination. That is too bad, and there are many situations where such combination is completely valid.

**Comment by acrylian** [comment] 2019-03-09 16:56
As said already I don't intend to abandon the native gettext for any workaround as I never had any problems neither with MAMP (which includes almost all locales) nor fairly standard  (shared) webservers that least included my local language plus English. It was almost never a big issue to ask support to enable others needed. If you cannot do this you most certainly cannot "disable any server gettext" either… It's up to the site owner to make sure his server can use what he intends to.

But back to this ticket. I cannot reproduce the http accept language not working. I have setup FIrefox with German first, US-English second and general English third:
![Bildschirmfoto 2019-03-09 um 17 46 32](https://user-images.githubusercontent.com/2474309/54074572-60509e80-4294-11e9-84ae-96c0a5b2930f.jpg)

Zenphoto itself is setup with German and English and http accept language enabled: 
![Bildschirmfoto 2019-03-09 um 17 46 13](https://user-images.githubusercontent.com/2474309/54074578-8118f400-4294-11e9-9185-ff961c2d55e5.jpg)

All works in Firefox, Chrome and Safari as expected for me.

**Closed** 2019-03-13 13:44 UTC
Labels: works as intended
