### ISSUE TITLE
Issue with keywords/tags (accents, capitalization, duplication etc)

### ISSUE THREAD

**Issue by kuz-z-zma** [zenphoto/zenphoto#1457] opened 2024-07-11 18:55 UTC
During testing of metadata import isses -  I've found an issue with keywords/tags (tested with xmp-metadata plugin enabled and disabled)
Photo: https://demo.private-universe.net/other-formats/languages/spire-of-sveta-petera-baznica.jpg.html

As you can see - image has name of the city in keywords written in 3 languages: Riga, Rīga, Рига
Now with each metadata refresh for this photo - Rīga doesn't get imported into tags, but is listed in keywords, but another "Riga" is added as a separate tag

![image](https://github.com/zenphoto/zenphoto/assets/75898540/a011a16a-3340-4e93-94ce-19bdc2110c4a)

Tags in admin lists 34 instances of Riga and none of Rīga
![image](https://github.com/zenphoto/zenphoto/assets/75898540/ce343698-cf11-46a4-b367-70a652726d30)

But there is only 1 image with those tags on my demo site and search finds that 1 image:
![image](https://github.com/zenphoto/zenphoto/assets/75898540/8745c343-96fb-4c56-a1bf-7603979e9168)

@acrylian 
I've certainty noticed just now - after multiple refreshes of metadata for the image on my test site.

But the presence of this same issue on my main site - where I did no metadata refreshes for Riga photos in last ~4 month signify the presence of issue before.
https://www.photo.private-universe.net/travel/latvia/riga/spire-of-sveta-petera-baznica.jpg.html

Images on the main site were imported on 23.12.2023 with current version of Zenphoto at a time, but I've clearly refreshed metadata for them at least once after that as there are now 3 tags of Riga for those photos. 
Can't pinpoint the time of that refresh though and I don't remember if Rīga ever was listed as a tag...

![image](https://github.com/zenphoto/zenphoto/assets/75898540/af139048-6439-4ee3-86a2-28697f55aacd)

tags show the same accented letter in other tags, so it's not the letter-only issue

@acrylian 34 duplicates on the demo site: every time I did a refresh of metadata in last months there - it adds one more Riga to an image.
(I've tested by refreshing metadata several times before reporting and got + 1 Riga each time)

> Or it is added because appears as a new metadata?

Probably Rīga (with an accent is seen as a new piece of metadata, new keyword - but it's added without accent and the cycle continues.

XMP plugin was disabled for testing, and I still got + 1 Riga

This is what helper plugin reports for the image:
```
EXIF

Array
(
    [FileName] => spire-of-sveta-petera-baznica.jpg
    [FileDateTime] => 1714940034
    [FileSize] => 380782
    [FileType] => 2
    [MimeType] => image/jpeg
    [SectionsFound] => ANY_TAG, IFD0, THUMBNAIL, EXIF, GPS
    [COMPUTED] => Array
        (
            [html] => width="800" height="600"
            [Height] => 600
            [Width] => 800
            [IsColor] => 1
            [ByteOrderMotorola] => 0
            [ApertureFNumber] => f/8.0
            [Copyright] => kuzzzma
            [Thumbnail.FileType] => 2
            [Thumbnail.MimeType] => image/jpeg
        )

    [Make] => Canon
    [Model] => Canon PowerShot G16
    [XResolution] => 72/1
    [YResolution] => 72/1
    [ResolutionUnit] => 2
    [Software] => Adobe Photoshop Lightroom Classic 13.0.2 (Windows)
    [DateTime] => 2023:12:23 18:27:59
    [Artist] => kuzzzma
    [Copyright] => kuzzzma
    [Exif_IFD_Pointer] => 276
    [GPS_IFD_Pointer] => 790
    [THUMBNAIL] => Array
        (
            [Compression] => 6
            [XResolution] => 72/1
            [YResolution] => 72/1
            [ResolutionUnit] => 2
            [JPEGInterchangeFormat] => 1110
            [JPEGInterchangeFormatLength] => 14135
        )

    [ExposureTime] => 1/160
    [FNumber] => 8/1
    [ISOSpeedRatings] => 125
    [UndefinedTag:0x8830] => 4
    [ExifVersion] => 0231
    [DateTimeOriginal] => 2014:05:05 11:34:30
    [DateTimeDigitized] => 2014:05:05 11:34:30
    [UndefinedTag:0x9010] => +03:00
    [ShutterSpeedValue] => 7321928/1000000
    [ApertureValue] => 6/1
    [ExposureBiasValue] => 0/3
    [MaxApertureValue] => 54/32
    [MeteringMode] => 5
    [Flash] => 16
    [FocalLength] => 6100/1000
    [ColorSpace] => 1
    [FocalPlaneXResolution] => 4000000/291
    [FocalPlaneYResolution] => 3000000/219
    [FocalPlaneResolutionUnit] => 2
    [SensingMethod] => 2
    [FileSource] => 
    [CustomRendered] => 0
    [ExposureMode] => 1
    [WhiteBalance] => 0
    [DigitalZoomRatio] => 4000/4000
    [SceneCaptureType] => 0
    [UndefinedTag:0xA432] => Array
        (
            [0] => 6100/1000
            [1] => 30500/1000
            [2] => 0/0
            [3] => 0/0
        )

    [UndefinedTag:0xA434] => 6.1-30.5 mm
    [GPSVersion] => 
    [GPSLatitudeRef] => N
    [GPSLatitude] => Array
        (
            [0] => 56/1
            [1] => 56/1
            [2] => 113422/2065
        )

    [GPSLongitudeRef] => E
    [GPSLongitude] => Array
        (
            [0] => 24/1
            [1] => 6/1
            [2] => 55255/1836
        )

    [GPSAltitudeRef] => 
    [GPSAltitude] => 14/1
    [GPSTimeStamp] => Array
        (
            [0] => 8/1
            [1] => 34/1
            [2] => 30/1
        )

    [GPSMapDatum] => WGS-84
    [GPSDateStamp] => 2014:05:05
)
IPTC

Array
(
    [1#090] => Array
        (
            [0] => %G
        )

    [1#000] => Array
        (
            [0] => 
        )

    [2#000] => Array
        (
            [0] => 
        )

    [2#005] => Array
        (
            [0] => Spire of Svētā Pētera baznīca
        )

    [2#025] => Array
        (
            [0] => architectural elements
            [1] => architecture
            [2] => churches
            [3] => cityscapes
            [4] => downtown
            [5] => Europe
            [6] => Latvia
            [7] => Latvija
            [8] => old town
            [9] => Riga
            [10] => Rīga
            [11] => spires
            [12] => spring
            [13] => St. Peter's Church
            [14] => streets
            [15] => Svētā Pētera baznīca
            [16] => towers
            [17] => travel
            [18] => Латвия
            [19] => Рига
        )

    [2#055] => Array
        (
            [0] => 20140505
        )

    [2#060] => Array
        (
            [0] => 113430
        )

    [2#062] => Array
        (
            [0] => 20140505
        )

    [2#063] => Array
        (
            [0] => 113430
        )

    [2#080] => Array
        (
            [0] => kuzzzma
        )

    [2#116] => Array
        (
            [0] => kuzzzma
        )

)
```

I've remembered - I had an issue that might be somewhat relevant.

I have a site with photos of Japanese dolls from my collection, and I use Japanese names for the characters in keywords/tags in conjunction with latin script.
In March I've added a photo of a doll named Gen (in Japanese script げん) - with both of those listed in image keywords.
Both were added as tags upon import of photo - so far no surprises there.

But in April I've added batch of photos of a doll Ken (in Japanese ケン) - and I noticed that ケン was not added to the tags, instead those photos were tagged with げん.

I couldn't get both tags to import in the end I've removed Gen photos and refreshed metadata for Ken - as this tag was more important to me, than I reuploaded Gen photo and now it's tagged as ケン.

Important info:
げん - hiragana script, each letter represents a syllable, in this case ge-n 
ケン - katakana script, each letter represents a syllable, in this case ke-n

け (without accent character!) means the same sound as ケ, but those scripts are not interchangeable, katakana is used for foreign loan words. 
Adding ゛(dakuten/accent) to  け - transforms it's pronunciation to "ge" - and once again those should be separate tags/keywords

Links for example images:
https://www.takara.private-universe.net/licca-family-dolls/triplets/licca-brother-gen-01.jpg.html
https://www.takara.private-universe.net/jenny-boyfriend-dolls/ken/ken-original/takara-ken-01.jpg.html
https://www.takara.private-universe.net/page/search/tags/%E3%82%B1%E3%83%B3/ - tag page

I've tried upload of a new photo on my test site
Image has tag Kaunas - I've added Kaūnas (u with an accent, this is not a real spelling of the city in Lithuanian, just for testing)
and got it imported without an accent - as a duplicate Kaunas
https://demo.private-universe.net/other-formats/languages/vilniaus-gatve-01.jpg.html

XMP is disabled, IPTC encoding is set to UTF-8, latest build from today
helper plugin report is interesting though:

```
EXIF

Array
(
    [FileName] => vilniaus-gatve-01.jpg
    [FileDateTime] => 1720542506
    [FileSize] => 505371
    [FileType] => 2
    [MimeType] => image/jpeg
    [SectionsFound] => ANY_TAG, IFD0, THUMBNAIL, EXIF, GPS, WINXP
    [COMPUTED] => Array
        (
            [html] => width="800" height="600"
            [Height] => 600
            [Width] => 800
            [IsColor] => 1
            [ByteOrderMotorola] => 1
            [ApertureFNumber] => f/8.0
            [Copyright] => kuzzzma
            [Thumbnail.FileType] => 2
            [Thumbnail.MimeType] => image/jpeg
        )

    [Make] => Canon
    [Model] => Canon PowerShot G16
    [XResolution] => 72/1
    [YResolution] => 72/1
    [ResolutionUnit] => 2
    [Software] => Adobe Photoshop Lightroom Classic 13.0.2 (Windows)
    [DateTime] => 2023:12:21 22:56:47
    [Artist] => kuzzzma
    [Copyright] => kuzzzma
    [Exif_IFD_Pointer] => 2360
    [GPS_IFD_Pointer] => 4948
    [Keywords] => ???????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????
    [UndefinedTag:0xEA1C] => �
    [THUMBNAIL] => Array
        (
            [Compression] => 6
            [XResolution] => 72/1
            [YResolution] => 72/1
            [ResolutionUnit] => 2
            [JPEGInterchangeFormat] => 5590
            [JPEGInterchangeFormatLength] => 12240
        )

    [ExposureTime] => 1/50
    [FNumber] => 8/1
    [ISOSpeedRatings] => 80
    [UndefinedTag:0x8830] => 4
    [ExifVersion] => 0231
    [DateTimeOriginal] => 2014:05:04 14:04:15
    [DateTimeDigitized] => 2014:05:04 14:04:15
    [UndefinedTag:0x9010] => +03:00
    [ShutterSpeedValue] => 5643856/1000000
    [ApertureValue] => 6/1
    [ExposureBiasValue] => -4/3
    [MaxApertureValue] => 85/32
    [MeteringMode] => 5
    [Flash] => 16
    [FocalLength] => 15910/1000
    [ColorSpace] => 1
    [FocalPlaneXResolution] => 4000000/291
    [FocalPlaneYResolution] => 3000000/219
    [FocalPlaneResolutionUnit] => 2
    [SensingMethod] => 2
    [FileSource] => 
    [CustomRendered] => 0
    [ExposureMode] => 1
    [WhiteBalance] => 0
    [DigitalZoomRatio] => 4000/4000
    [SceneCaptureType] => 0
    [UndefinedTag:0xA432] => Array
        (
            [0] => 6100/1000
            [1] => 30500/1000
            [2] => 0/0
            [3] => 0/0
        )

    [UndefinedTag:0xA434] => 6.1-30.5 mm
    [GPSVersion] => 
    [GPSLatitudeRef] => N
    [GPSLatitude] => Array
        (
            [0] => 54/1
            [1] => 53/1
            [2] => 69163/1397
        )

    [GPSLongitudeRef] => E
    [GPSLongitude] => Array
        (
            [0] => 23/1
            [1] => 53/1
            [2] => 110182/2049
        )

    [GPSAltitudeRef] => 
    [GPSAltitude] => 30/1
    [GPSTimeStamp] => Array
        (
            [0] => 11/1
            [1] => 4/1
            [2] => 15/1
        )

    [GPSMapDatum] => WGS-84
    [GPSDateStamp] => 2014:05:04
)
IPTC

Array
(
    [1#090] => Array
        (
            [0] => %G
        )

    [1#000] => Array
        (
            [0] => 
        )

    [2#000] => Array
        (
            [0] => 
        )

    [2#005] => Array
        (
            [0] => Vilniaus gatvė
        )

    [2#025] => Array
        (
            [0] => Europe
            [1] => Kaunas
            [2] => Lietuva
            [3] => Lithuania
            [4] => Vilniaus gatvė
            [5] => architecture
            [6] => cityscapes
            [7] => grass
            [8] => old town
            [9] => pedestrian streets
            [10] => plants
            [11] => spring
            [12] => streets
            [13] => travel
            [14] => trees
            [15] => Каунас
            [16] => Литва
            [17] => Kaūnas
        )

    [2#055] => Array
        (
            [0] => 20140504
        )

    [2#060] => Array
        (
            [0] => 140415
        )

    [2#062] => Array
        (
            [0] => 20140504
        )

    [2#063] => Array
        (
            [0] => 140415
        )

    [2#080] => Array
        (
            [0] => kuzzzma
        )

    [2#116] => Array
        (
            [0] => kuzzzma
        )

)
```

> Not sure if I understand right. Should that be three tags actually?

I mean, those can't be combined into one tag - those characters are completely separate in Japanese, so  げん  and けん and ケン all should be different tags

I've added a test image with japanese to my test site - 
https://demo.private-universe.net/other-formats/languages/gen-test.jpg.html

I've added all げん  and けん and ケン  to the keywords
Keywords: | dolls, Gen, Licca family, Takara, Triplets, ケン, けん, げん, タカラ

and got 
![image](https://github.com/zenphoto/zenphoto/assets/75898540/ed67ad5e-9a34-4a56-9ee3-aa31f8b6e958)

https://demo.private-universe.net/other-formats/languages/vilniaus-gatve-02.jpg.html
I've added Kaūnasū to keywords and it got added as tag, 

So I've added a keyword with another letter changed Kaūnaš - and it got me another Kaunas
https://demo.private-universe.net/other-formats/languages/vilniaus-gatve-03.jpg.html

It seems that only keywords with same number of letters and only difference being accented characters are affected.

https://demo.private-universe.net/other-formats/languages/gen-test-2.jpg.html

Did the same for Japanese - adding another letter げんけ allowed tag to be added 

_Originally posted by @kuz-z-zma - you can read start of discussion here.
https://github.com/zenphoto/zenphoto/issues/1452#issuecomment-2217722424_

**Comment by sbillard** [comment] 2024-07-11 19:53
There is a reason why MySQL does case insensitive/accent insensitive comparisons. These comparisons are primarily used in searches. In most instances humans expect that a search for "candy" would match any permutation of the case of the letters. Clearly MySQL thinks that accents should be treated the same.

The primary use of tags in zenphoto is for organization, e.g. searching, so the same analysis applies. That was the premises for lower casing the tag when checking for duplicates. The tags are stored as entered since that is the presumed display version.

Unfortunately the PHP lowercasing is not equivalent to the MySQL behavior. This results in the code failing to detect that an object already has the tag assigned and causes the buildup of duplicate entries. (probably the obj_to_tag trupple should be an unique key.)

**Comment by acrylian** [comment] 2024-07-12 06:37
To add up as discussed on #1452 previously, the reason for the issue is that the database uses `_ci` collations (we do set that via setup but it is the default everywhere, too). Technically there are collations that are case sensitiive and accent sensitive: https://dev.mysql.com/doc/refman/5.7/en/charset-collation-names.html But these are not generally available on standard servers, at least on none of ours. 

The workaround seems to be to use a `_bin` collation for tags instead which arises other problems as any case difference and any accent would result in a new tag possible. On multiuser sites with users that do not know about this this can cause serious data trouble and no one should need to care about all that adding tags.

MySQL does have its own lowercase function. It does not work on binary data itself. According to https://dev.mysql.com/doc/refman/8.4/en/string-functions.html#function_lower the data needs to be converted first using this example query `SELECT LOWER(@str), LOWER(CONVERT(@str USING utf8mb4));` to work. Perhaps its behaviour may be of help here and should be tested.

**Comment by bic-ed** [comment] 2024-07-12 06:46
I generally agree with sbillard thoughts on search, though tags are special search tools so the approach could be different, given the possibility to also use the tag_suggest plugin that can resolve case ambiguity. But That's a matter of choice. In any case, if we decide to leave things as they are now (ci, ai), we can use the bin collate directly in the query to avoid duplicates. Be like:

```php
WHERE `name` COLLATE utf8mb4_bin = $_zp_db->quote($key)
``` 
and skipping the lowercase as well

**Comment by bic-ed** [comment] 2024-07-12 07:31
I can confirm that changing this line
https://github.com/zenphoto/zenphoto/blob/961c4958ccbc094b5254a502ffb81351cce06246/zp-core/functions/functions.php#L1245
to
```php
$dbtag = $_zp_db->querySingleRow("SELECT `id` FROM " . $_zp_db->prefix('tags') . " WHERE `name` COLLATE utf8mb4_bin =" . $_zp_db->quote($key));
``` 
solves the issue of duplicating tags on metadata import, leaving all the rest as is now, so this could be a temporary fix until we decide the best approach to use with tags,

**Comment by acrylian** [comment] 2024-07-12 07:37
I agree to the search topic as well. In German we often are lazy - as anyone elase - and write words that actually have accent without and expect that to be the "same". 

We had an example of names that are also flower names like Rose and rose.  this is reallly a semantic difference code does not understand anyway as technically it IS the same word. And the e.g. Japanese word issue is quite specific to that language and as I mentioned over there a native speaker with its site in Japanese might have to do things differently anyway.    Hate to say it but our main user base is (Western) European according to access stats, too.

@bic-ed If that solution has now other disavantages like speed with thousands of tags, that seems to be a good way. A common lowest dominatior so to speak.

**Comment by bic-ed** [comment] 2024-07-12 07:43
> @bic-ed If that solution has no other disavantages like speed with thousands of tags, that seems to be a good way. A common lowest dominatior so to speak.

I can't tell, I'm not an sql expert at all. What it does is to force the collation for that very query alone. Possibly the collation has not heavy impact on speed? Furthermore, the lowercase comparision could be skipped  as well, given the cs collation.

**Comment by bic-ed** [comment] 2024-07-12 09:06
Are you talking about the `if (isset($_GET['newtags'])) {` part, right?
As far as I can see, in the admin page there is no need to force the collation, as tags differing for accent or case from any existing one are already discarded. The problem only arises when automatically importing tags from metadata.

**Comment by bic-ed** [comment] 2024-07-12 09:43
In admin panel, the only different behavior I found so far with the above change is on individual item pages. If you try to add to an item a new tag, differing from an existing one for accent only, the existing tag is not anymore associated to the item as it happened before the change (which was weird anyway). The adding is simply ignored, likewise it happens in the general tags tab when you try to do the same.

**Comment by acrylian** [comment] 2024-07-12 10:35
> Are you talking about the if (isset($_GET['newtags'])) { part, right?

I really didn't look at anything in detail. We just need to be sure that adding, deleting and renaming targets the right tags. It should not make any difference how a tag is added. 

On the interface on an item also JS comes in which of course also compares if a tag is already assigned. That also need to be aware of any change. You can also create new tags here, too.

**Comment by bic-ed** [comment] 2024-07-12 12:47
I've tested all @acrylian suggested and all came up to my mind, I'm pretty sure that with the storeTags() function rewritten as follows (where I also removed the redundant lowercase transform and renamed some variables consequently for readability), there will be no duplicated tags on metadata import and all the rest will remain the same, except for the different behavior, as [mentioned above](https://github.com/zenphoto/zenphoto/issues/1457#issuecomment-2225211184), on adding a new tag which differs only for an accent from an existing one when in an item admin page. In such a case, perhaps a message should be shown, likewise in the general tags tab, where at the moment when a new tag is not actually added because existing identical or existing in a different case/accent combination, the message shown is always: _New tags added_.

If anybody else wants to test:
```php
function storeTags($tags, $id, $tbl) {
  global $_zp_db;
  if ($id) {
    $not_empty_tags = array();
    foreach ($tags as $key => $tag) {
      $tag = trim($tag);
      if (!empty($tag)) {
        if (!in_array($tag, $not_empty_tags)) {
          $not_empty_tags[$tag] = $tag;
        }
      }
    }
    $sql = "SELECT `id`, `tagid` from " . $_zp_db->prefix('obj_to_tag') . " WHERE `objectid`='" . $id . "' AND `type`='" . $tbl . "'";
    $result = $_zp_db->query($sql);
    $existing = array();
    if ($result) {
      while ($row = $_zp_db->fetchAssoc($result)) {
        $dbtag = $_zp_db->querySingleRow("SELECT `name` FROM " . $_zp_db->prefix('tags') . " WHERE `id`='" . $row['tagid'] . "'");
        $existing_name = $dbtag['name'];
        if (in_array($existing_name, $not_empty_tags)) { // tag already set no action needed
          $existing[] = $existing_name;
        } else { // tag no longer set, remove it
          $_zp_db->query("DELETE FROM " . $_zp_db->prefix('obj_to_tag') . " WHERE `id`='" . $row['id'] . "'");
        }
      }
      $_zp_db->freeResult($result);
    }
    $tags = array_diff($not_empty_tags, $existing); // new tags for the object
    foreach ($tags as $key => $tag) {
      $dbtag = $_zp_db->querySingleRow("SELECT `id` FROM " . $_zp_db->prefix('tags') . " WHERE `name` COLLATE utf8mb4_bin =" . $_zp_db->quote($key));
      if (!is_array($dbtag)) { // tag does not exist
        $_zp_db->query("INSERT INTO " . $_zp_db->prefix('tags') . " (name) VALUES (" . $_zp_db->quote($key) . ")", false);
        $dbtag = array('id' => $_zp_db->insertID());
      }
      $_zp_db->query("INSERT INTO " . $_zp_db->prefix('obj_to_tag') . "(`objectid`, `tagid`, `type`) VALUES (" . $id . "," . $dbtag['id'] . ",'" . $tbl . "')");
    }
  }
}

```

**Comment by acrylian** [comment] 2024-07-12 14:48
Thanks, will test it.

**Comment by acrylian** [comment] 2024-07-12 15:07
Seems to work regarding duplicates via meta refresh. I get a notice in the log though:

    WARNING: Trying to access array offset on value of type null in /Users/maltemuller/htdocs/zenphoto-dev/zp- core/functions/functions.php on line 1233
    storeTags called from ThemeObject->setTags (class-themeobject.php [210])
    from Image->updateMetaData (class-image.php [426])
    from Gallery->garbageCollect (class-gallery.php [922])
    from admin-refresh-metadata.php [33] 

That's these lines but that must be older as that is not new.

     $dbtag = $_zp_db->querySingleRow("SELECT `name` FROM " . $_zp_db->prefix('tags') . " WHERE `id`='" . $row['tagid'] . "'");
     $existing_name = $dbtag['name'];

**Comment by bic-ed** [comment] 2024-07-12 15:15
Ah yes, I've tested now also with the unchanged version of storeTags() and the warning is still there.

**Comment by bic-ed** [comment] 2024-07-12 15:20
Actually I get some deprecated as well with the unchanged version
DEPRECATED: mb_strtolower(): Passing null to parameter #1 ($string) of type string is deprecated in C:\wamp64\www\zenphoto\zp-core\functions\functions.php on line 1234

**Comment by acrylian** [comment] 2024-07-12 15:42
> Actually I get some deprecated as well with the unchanged version

**Comment by bic-ed** [comment] 2024-07-12 15:55
Looking at the zp_obj_to_tag table, I'm getting some elements with tagid=0, but there is not such an id in my zp_tags table.
Now I have to give up for a while, later I'll check if this happens also with the unchanged version of storeTags()

**Comment by acrylian** [comment] 2024-07-12 16:27
"tagid" is from the obj_to_tags tables. I just tried the original version and now I get this there as well. Never noticed before. But the queries are the same anyway unless I miss anything.

But more on the weekend probably…

**Comment by bic-ed** [comment] 2024-07-12 19:07
> "tagid" is from the obj_to_tags tables.

Yes, I was trying to say that there is not a corresponding id=0 in zp_tags table, sorry for the typo.
That said, I discovered that the warning comes from there anyway. If I delete the entry with tagid=0 from the zp_obj_to_tag table and make a metadata refresh on one single image, no warnings appear in log but the tagid=0 entry appears again in that table. When I make a metadata refresh with the phantom tag in zp_obj_to_tag, the warnings spots out again.

**Comment by bic-ed** [comment] 2024-07-12 19:45
First thing I try is preventing the insertion of an entry with tagid=0 in zp_obj_to_tag table, as follows:
```php
if ($dbtag['id']) {
  $_zp_db->query("INSERT INTO " . $_zp_db->prefix('obj_to_tag') . "(`objectid`, `tagid`, `type`) VALUES (" . $id . "," . $dbtag['id'] . ",'" . $tbl . "')");
}
```
even though I have no idea why such a tagid is generated by the above line:
```php
$dbtag = array('id' => $_zp_db->insertID());
```

**Comment by bic-ed** [comment] 2024-07-13 07:08
> even though I have no idea why such a tagid is generated by the above line:

Actually it does not come from $_zp_db->insertID() but from the previous query, with or without the forced collation:

```php
$dbtag = $_zp_db->querySingleRow("SELECT `id` FROM " . $_zp_db->prefix('tags') . " WHERE `name` COLLATE utf8mb4_bin =" . $_zp_db->quote($key));

```

**Comment by acrylian** [comment] 2024-07-13 07:18
Weird, `insertID()` is supposed to return the id of that last insert into the table. It would return 0 if there is no db handler active (see the dbbase class) or if no connection is available. 

I think your fix is correct as we only should assign the tag if it is actually there, either already or just being added. then the tagid would be an actual id. Must be a very old bug as in my memory this code is there for ages…

**Comment by bic-ed** [comment] 2024-07-13 07:34
Just a side note for future discussions.  
Talking again about the tag approach in general, I've looked at the behavior of a bigger CMS. They don't allow tags differing in letter case, but do allow tags differing in accents.

**Comment by acrylian** [comment] 2024-07-13 07:44
> Actually it does not come from $_zp_db->insertID() but from the previous query, with or without the forced collation:

I think it's connected. First qurey checks for existance. If there is no tag there is no id. If it is then inserted and not successful there is also no (new) id. In that case the assignment query should not happen at all.

> Talking again about the tag approach in general, I've looked at the behavior of a bigger CMS. They don't allow tags differing in letter case, but do allow tags differing in accents.

That makes sense. But that might be easier once we have a multilingual tags with separate title and name. For example WP as the most used one does of course.

**Comment by acrylian** [comment] 2024-07-13 07:45
I would say commit you fixes so far.

**Comment by bic-ed** [comment] 2024-07-13 07:47
Ok, I'll do it later today.

**Comment by kuz-z-zma** [comment] 2024-07-13 07:54
>  They don't allow tags differing in letter case, but do allow tags differing in accents.

You mean links to tags or DB storage?
Because display/presentation on frontend - usually allows for capitalisation

**Comment by acrylian** [comment] 2024-07-13 08:04
URLs generally are and should be all lowercase. WP has independent titles that can be anything and URL names. That is what we have on all other items expect tags currently, too.

**Comment by acrylian** [comment] 2024-07-13 08:07
If a title like word with or without accent would create a duplicate name, the name is numbered or has manually to be changed to be otherwise unique. Again our tags are special currently since title=name.

**Comment by bic-ed** [comment] 2024-07-13 08:15
> You mean links to tags or DB storage?
> Because display/presentation on frontend - usually allows for capitalisation

No, I mean you can have capitalized tags, but once you have one you can't have the same lowercase.
For instance, if you have a tag named Home you cannot have home, and viceversa. But I didn't actually check. 
In any case for presentation you can use css for capitalize tags.

**Comment by acrylian** [comment] 2024-07-13 08:22
> No, I mean you can have capitalized tags, but once you have one you can't have the same lowercase.
For instance, if you have a tag named Home you cannot have home, and viceversa. But I didn't actually check.
In any case for presentation you can use css for capitalize tags.

Which matches the way it works/will work with title + name as the URL name is lowercase, "cleared" and "case insenstivie" but the title can be captilaized and else

**Comment by bic-ed** [comment] 2024-07-13 08:32
I've committed the changes discussed in this issue:
ff4ec0e

**Comment by kuz-z-zma** [comment] 2024-07-13 09:12
Tested latest version - My accented tags that are too close for unaccented ones now are not imported at all (instead of creating two similar tags per image - Riga and Rīga result only in 1 Riga tag), and there is no further duplication upon metadata refresh.

So this part is fixed hopefully.

**Comment by acrylian** [comment] 2024-07-13 09:27
Good, might be the closest we get to this for now.

**Comment by kuz-z-zma** [comment] 2024-07-13 09:56
At least people won't get duplicates after refresh to fix not imported metadata.

**Closed** 2024-07-27 09:35 UTC
