### ISSUE TITLE
Backup restore is broken?

### ISSUE THREAD

**Issue by thany** [zenphoto/zenphoto#1216] opened 2019-02-26 23:32 UTC
I've restored a backup I made on my live server, and restored it on my XAMPP setup. It appeared to work. I used the default built-in backup/restore functionality on a fresh zenphoto installation.

Now the whole damn site is broken. EVERY request is responded to with the html representing homepage. So I'm not getting any CSS - I'm getting the homepage instead. I'm not getting into the admin panels, I'm not getting into the setup, **EVERYTHING** is now the homepage. Every single request of any type to any location from any browser.

Except a test.php containing a `phpinfo()` - that one still works.

**Comment by acrylian** [comment] 2019-02-27 09:23
You surely followed the instructions on our site, did you? The order of doing things is important. If you don't get any CSS that indicates other problems you surely reviewed the logs about.

The database backup tool does work. However setting it to compressed backup does not on all servers (as on ours).

**Comment by kochs-online** [comment] 2019-02-27 11:39
@thany Do you have access to the server logs (like Apache's `access_log` and `error_log`)? Can you provide the HTTP response headers from the browser or the ouput of `wget -S --spider <Zenphoto URI>`?

**Comment by acrylian** [comment] 2019-02-27 11:48
You can also use this tool to list the locales the server actually supports:
https://github.com/zenphoto/Unsupported/blob/master/misc/list_locales/list_locales.php

**Comment by thany** [comment] 2019-02-27 12:00
I'm not sure if I can (or should) still reproduce this problem. I've started over, reminding myself not to run a restore, but just to copy over the album manually. I only needed to copy some stuff over to setup a working development environment anyway.

What might remain is for zenphoto to display error messages instead of just nilly-willy outputting the homepage for each and every request. Most of the time, not rendering a big phat error message is very undesirable. It may *seem* like a good idea to, in case of some problem, render something that doesn't look broken, but it's not.

**Comment by kochs-online** [comment] 2019-02-27 12:11
> What might remain is for zenphoto to display error messages instead of just nilly-willy outputting the homepage for each and every request.

Well, that depends on the cause of this issue. If Zenphoto does not "know" that there is an error (e.g. when `.htaccess` got corrupted), it cannot show an error message.

> Most of the time, not rendering a big phat error message is very undesirable.

Yeah, you're right about that.

**Comment by acrylian** [comment] 2019-02-27 12:32
This all sounds like the local server environment is not working correctly. If you see error message output that is most likey a server setting.

**Comment by thany** [comment] 2019-02-28 22:33
> Well, that depends on the cause of this issue. If Zenphoto does not "know" that there is an error (e.g. when `.htaccess` got corrupted), it cannot show an error message.

I was able to get into zenphoto to perform the restore, so the server was working fine, and the .htaccess was valid. I'm assuming a restore doesn't overwrite any server settings, and doesn't (erronously) rewrite the .htaccess.

> This all sounds like the local server environment is not working correctly. If you see error message output that is most likey a server setting.

The server won't stop working after restoring a backup, would it? It's just writing stuff to the database, isn't it? So, if that went wrong for some reason, it *could* display the SQL error, if any. Or some error returned by mysqli. And yes, PHP error display is enabled, as the setup even warning me about it. So I should've seen them.

**Comment by acrylian** [comment] 2019-03-01 09:18
The utility clearly tells it is about the database backup only and naturally you need to have backups using the backup tool:

> The backup facility creates database snapshots in the backup folder of your installation. These backups are named in according to the date and time the backup was taken.

**Comment by thany** [comment] 2019-03-01 12:57
Exactly, so the restore utility shouldn't be able to break the zenphoto installation as catastrophically as it did...

**Comment by acrylian** [comment] 2019-03-01 13:24
Well, not all servers (and users) are the same. Impossible to cover everything. I will close this ticket.

**Closed by acrylian** 2019-03-01 13:24 UTC
