### ISSUE TITLE
1.6RC Setup Shows Errors During Table Creation

### ISSUE THREAD

**Issue by MarkRH** [zenphoto/zenphoto#1348] opened 2022-11-22 22:14 UTC
Decided to try out the 1.6a master in it's own directory on my PC running PHP 8.1.12.  I did not place it into my existing installation.  Would this have caused some files to be missing? 

I got several errors similar to the following during the setup processes:

Table creation failure:
`Query: CREATE TABLE IF NOT EXISTS `options` ( `id` int(11) UNSIGNED NOT NULL auto_increment, `ownerid` int(11) UNSIGNED NOT NULL DEFAULT 0, `name` varchar(191) NOT NULL, `value` text, `theme` varchar (127) NOT NULL, `creator` varchar (255) DEFAULT NULL, PRIMARY KEY (`id`), UNIQUE (`name`, `ownerid`, `theme`) ) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;`
Error: Specified key was too long; max key length is 1000 bytes

Another table:
Table creation failure:
`Query: CREATE TABLE IF NOT EXISTS `tags` ( `id` int(11) UNSIGNED NOT NULL auto_increment, `name` varchar(255) NOT NULL, PRIMARY KEY (`id`), UNIQUE (`name`) ) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;`
Error: Specified key was too long; max key length is 1000 bytes

Other tables such as comments it made fine.  Not sure if this is a problem with some setting in MariaDB or what?  Any idea what to look at?

Thanks for your efforts.

**Comment by MarkRH** [comment] 2022-11-22 22:28
I tried manually creating the options table using a SQL editor and got the same error.  So, this also happens outside of your setup script.  Hmmm..

**Comment by MarkRH** [comment] 2022-11-22 23:16
Well.. looks like this is related to the default table type on my local system being Aria.  At my Webhost the default is InnoDB and the query executes fine.  If I try to change the table to Aria after it has been created, then I get the same error.  Something to do with the length of the name column and the collation after looking up the error.  

So, looks like I'll need to change my default table type locally to InnoDB instead and see what happens.

**Comment by acrylian** [comment] 2022-11-23 08:40
Thank for testing. That's actually a bug. We were a bit too focussed on updating and also all our database use innodb by default since forever. Setup does fix those too long indexes on updates but of course on fresh creation it never gets that far.  It's actually a duplicate of https://github.com/zenphoto/zenphoto/issues/1342

**Comment by acrylian** [comment] 2022-11-23 12:51
I committed something. It works on my local server. Please try if it fixes your issue with a fresh install

**Comment by bic-ed** [comment] 2022-11-23 16:39
While I was able to upgrade flawlessly on my live test server, I get a conversion error when I try to run setup on my local server. 

 {2536:Wed, 23 Nov 2022 16:35:03 GMT}

USER ERROR: mysqli Error: ( ALTER TABLE zp_news_categories CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci ) failed. mysqli returned the error Specified key was too long; max key length is 1000 bytes in C:\wamp64\www\zenphoto\zp-core\classes\class-dbmysqli.php on line 80

trigger_error called from dbMySQLi->query (class-dbmysqli.php [80])

from dbBase->convertTableToUtf8mb4 (class-dbbase.php [907])

from index.php [2446]

**Comment by acrylian** [comment] 2022-11-23 17:01
Yes, this is more for the fresh install. But on an update this should not possible to happen. We first set new indexes and then convert tables.

You are really using the latest master (1.6RC)?

**Comment by acrylian** [comment] 2022-11-23 17:04
Please look into the database via phpmyadmin how the keys for that table are defined. That should look like this:
![Bildschirmfoto 2022-11-23 um 18 04 38](https://user-images.githubusercontent.com/2474309/203606772-02635562-8cd8-4680-a361-af12db103cf7.jpg)

**Comment by bic-ed** [comment] 2022-11-23 17:21
Yes, updated after your latest commits.
I have 3 lines there though
![Screenshot 2022-11-23 at 18-19-55 localhost _ MySQL _ zenphoto _ zp_news_categories phpMyAdmin 5 2 0](https://user-images.githubusercontent.com/2939831/203609634-3781eeaa-40cb-4132-b5b0-1cbbfdb91f3e.png)

**Comment by MarkRH** [comment] 2022-11-23 17:22
I downloaded the lastest update and ran setup again.  This time it installed without issue after making sure the default engine was InnoDB.  I'll make new topics for other issues I'm running into, such as the RSS part not seeming to work.

**Comment by acrylian** [comment] 2022-11-23 17:36
The three lines are wrong actually and may be the relict of something older…

Please don't test with Innodb if you usually use something else. We really like this to work with innodib, mysiam or else (you mentioned "Aria" which I never heard of I admit).

**Comment by bic-ed** [comment] 2022-11-23 18:02
Yes, locally I have a very old installation, starting from v1.2 or so...
On the live server there are only the two expected lines. How to get rid of the third one on local?  
![Screenshot 2022-11-23 at 18-59-41 www antonioranesi it _ localhost _ antonioranesi _ zp_news phpMyAdmin 5 2 0](https://user-images.githubusercontent.com/2939831/203617037-28f5ac4e-6132-4191-bffc-54be82256f5e.png)

**Comment by acrylian** [comment] 2022-11-23 18:03
You need to have the titlelink(191) one with 1.6RC. You can manually delete the other one.

**Comment by acrylian** [comment] 2022-11-23 18:04
> You need to have the titlelink(191) one with 1.6RC. 

That's of course just titlelink on 1.5.9 before the index adjustments of utf8mb4.

**Comment by bic-ed** [comment] 2022-11-23 18:05
Yes, the latter screen is from the production server, where I didn't update yet

**Comment by bic-ed** [comment] 2022-11-23 18:07
Ok, after deleting the intruding line I was able to upgrade. Thanks!

**Comment by MarkRH** [comment] 2022-11-23 18:53
> The three lines are wrong actually and may be the relict of something older…
> 
> Please don't test with Innodb if you usually use something else. We really like this to work with innodib, mysiam or else (you mentioned "Aria" which I never heard of I admit).

When I first ran the setup, I had left the default database engine set to Aria (it's like MyIsam), and just about everything complained about indexes being to long, over 1000 bytes.  After setting the default to InnoDB then it ran fine.  

Now what's interesting is that it let me manually change all the tables to Aria without complaining and the Gallery still loads and seems to work fine.  So.. I can try it again with the engine set back to Aria as default and show you the errors I get.

**Comment by acrylian** [comment] 2022-11-23 19:08
> When I first ran the setup, I had left the default database engine set to Aria (it's like MyIsam), and just about everything complained about indexes being too long, over 1000 bytes. After setting the default to InnoDB then it ran fine.

I know that was for the table creation and before I fixed the initial index defines for new tables. Setup has update query for changing the indexes which on your first run was not reached but now.

So please try a fresh install with an empty database with Aria again. We need to know if that now works.

**Comment by MarkRH** [comment] 2022-11-23 21:19
Okay.  Ran a fresh install with the database engine set back to Aria as default.  Note: On my Webhost their default engine is InnoDB so if I'm trying to match what my Webhost is doing then I probably should as well in the end.  But, can do this for testing.  I can also try MyISAM to see what happens with it.  These are the table creation errors I got:

```
Table creation failure:
Query: CREATE TABLE IF NOT EXISTS `options` ( `id` int(11) UNSIGNED NOT NULL auto_increment, `ownerid` int(11) UNSIGNED NOT NULL DEFAULT 0, `name` varchar(191) NOT NULL, `value` text, `theme` varchar (127) NOT NULL, `creator` varchar (255) DEFAULT NULL, PRIMARY KEY (`id`), UNIQUE (`name`, `ownerid`, `theme`) ) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;
Error: Specified key was too long; max key length is 1000 bytes

Table creation failure:
Query: CREATE TABLE IF NOT EXISTS `tags` ( `id` int(11) UNSIGNED NOT NULL auto_increment, `name` varchar(255) NOT NULL, PRIMARY KEY (`id`), UNIQUE (`name`) ) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;
Error: Specified key was too long; max key length is 1000 bytes

Table creation failure:
Query: CREATE TABLE IF NOT EXISTS `albums` ( `id` int(11) UNSIGNED NOT NULL auto_increment, `parentid` int(11) unsigned default NULL, `folder` varchar(255) NOT NULL default '', `title` text, `desc` text, `date` datetime default NULL, `updateddate` datetime default NULL, `location` text, `show` int(1) unsigned NOT NULL default '1', `closecomments` int(1) unsigned NOT NULL default '0', `commentson` int(1) UNSIGNED NOT NULL default '1', `thumb` varchar(255) default NULL, `mtime` int(32) default NULL, `sort_type` varchar(20) default NULL, `subalbum_sort_type` varchar(20) default NULL, `sort_order` int(11) unsigned default NULL, `image_sortdirection` int(1) UNSIGNED default '0', `album_sortdirection` int(1) UNSIGNED default '0', `hitcounter` int(11) unsigned default 0, `password` varchar(255) NOT NULL DEFAULT '', `password_hint` text, `publishdate` datetime default NULL, `expiredate` datetime default NULL, `total_value` int(11) DEFAULT 0, `total_votes` int(11) DEFAULT 0, `used_ips` longtext, `custom_data` text, `dynamic` int(1) DEFAULT 0, `search_params` text, `album_theme` varchar(127), `user` varchar(64), `rating` float, `rating_status` int(1) DEFAULT 3, `watermark` varchar(255), `watermark_thumb` varchar(255), `owner` varchar(64) DEFAULT NULL, `codeblock` text, PRIMARY KEY (`id`), UNIQUE `folder` (`folder`) ) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;
Error: Specified key was too long; max key length is 1000 bytes

Table creation failure:
Query: CREATE TABLE IF NOT EXISTS `images` ( `id` int(11) UNSIGNED NOT NULL auto_increment, `albumid` int(11) unsigned NOT NULL default '0', `filename` varchar(255) NOT NULL default '', `title` text, `desc` text, `location` text, `city` tinytext, `state` tinytext, `country` tinytext, `credit` text, `copyright` text, `commentson` int(1) UNSIGNED NOT NULL default '1', `show` int(1) NOT NULL default '1', `date` datetime default NULL, `sort_order` int(11) unsigned default NULL, `height` int(10) unsigned default NULL, `width` int(10) unsigned default NULL, `thumbX` int(10) unsigned default NULL, `thumbY` int(10) unsigned default NULL, `thumbW` int(10) unsigned default NULL, `thumbH` int(10) unsigned default NULL, `mtime` int(32) default NULL, `publishdate` datetime default NULL, `expiredate` datetime default NULL, `hitcounter` int(11) unsigned default 0, `total_value` int(11) unsigned default '0', `total_votes` int(11) unsigned default '0', `used_ips` longtext, `custom_data` text, `rating` float, `rating_status` int(1) DEFAULT 3, `hasMetadata` int(1) DEFAULT 0, `watermark` varchar(255) DEFAULT NULL, `watermark_use` int(1) DEFAULT 7, `owner` varchar(64) DEFAULT NULL, `filesize` int(11), `codeblock` text, `user` varchar(64) DEFAULT NULL, `password` varchar(64) DEFAULT NULL, `password_hint` text, PRIMARY KEY (`id`), KEY (`albumid`), UNIQUE `filename` (`filename`,`albumid`) ) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;
Error: Specified key was too long; max key length is 1000 bytes

Table creation failure:
Query: CREATE TABLE IF NOT EXISTS `news` ( `id` int(11) UNSIGNED NOT NULL auto_increment, `title` text, `content` longtext, `extracontent` text, `show` int(1) unsigned NOT NULL default '1', `date` datetime, `titlelink` varchar(255) NOT NULL, `commentson` int(1) UNSIGNED NOT NULL, `codeblock` text, `author` varchar(64) NOT NULL, `lastchange` datetime default NULL, `lastchangeauthor` varchar(64) NOT NULL, `hitcounter` int(11) unsigned default 0, `permalink` int(1) unsigned NOT NULL default 0, `locked` int(1) unsigned NOT NULL default 0, `expiredate` datetime default NULL, `total_value` int(11) unsigned default '0', `total_votes` int(11) unsigned default '0', `used_ips` longtext, `rating` float, `rating_status` int(1) DEFAULT 3, `sticky` int(1) DEFAULT 0, `custom_data` text, `truncation` int(1) unsigned default 0, PRIMARY KEY (`id`), UNIQUE (`titlelink`) ) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;
Error: Specified key was too long; max key length is 1000 bytes

Table creation failure:
Query: CREATE TABLE IF NOT EXISTS `news_categories` ( `id` int(11) UNSIGNED NOT NULL auto_increment, `title` text, `titlelink` varchar(255) NOT NULL, `permalink` int(1) UNSIGNED NOT NULL default 0, `hitcounter` int(11) unsigned default 0, `user` varchar(64) DEFAULT NULL, `password` varchar(64) DEFAULT NULL, `password_hint` text, `parentid` int(11) DEFAULT NULL, `sort_order` varchar(48) DEFAULT NULL, `desc` text, `custom_data` text, `show` int(1) unsigned NOT NULL default '1', PRIMARY KEY (`id`), UNIQUE (`titlelink`) ) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;
Error: Specified key was too long; max key length is 1000 bytes

Table creation failure:
Query: CREATE TABLE IF NOT EXISTS `pages` ( `id` int(11) UNSIGNED NOT NULL auto_increment, `parentid` int(11) unsigned default NULL, `title` text, `content` longtext, `extracontent` text, `sort_order`varchar(48) NOT NULL default '', `show` int(1) unsigned NOT NULL default '1', `titlelink` varchar(255) NOT NULL, `commentson` int(1) unsigned NOT NULL, `codeblock` text, `author` varchar(64) NOT NULL, `date` datetime default NULL, `lastchange` datetime default NULL, `lastchangeauthor` varchar(64) NOT NULL, `hitcounter` int(11) unsigned default 0, `permalink` int(1) unsigned NOT NULL default 0, `locked` int(1) unsigned NOT NULL default 0, `expiredate` datetime default NULL, `total_value` int(11) unsigned default '0', `total_votes` int(11) unsigned default '0', `used_ips` longtext, `rating` float, `rating_status` int(1) DEFAULT 3, `user` varchar(64) DEFAULT NULL, `password` varchar(64) DEFAULT NULL, `password_hint` text, `custom_data` text, `truncation` int(1) unsigned default 0, PRIMARY KEY (`id`), UNIQUE (`titlelink`) ) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;
Error: Specified key was too long; max key length is 1000 bytes
```

These are the tables it did create:

![image](https://user-images.githubusercontent.com/8035962/203647484-533206e0-78b9-43bf-9f1d-1bb92296f859.png)

The end of the installation process after the errors shows:

![image](https://user-images.githubusercontent.com/8035962/203647707-d851a79b-52f9-40f7-b2d3-311c9f35c6fa.png)

If there anything you'd like me to check or try let me know.

**Comment by MarkRH** [comment] 2022-11-23 21:34
Just for the heck of it I tried a fresh install with the default table type set to MyISAM and I got the same errors with the same tables.  Unless I missed the newer files when I re-downloaded the master I can try and get it again.

**Comment by acrylian** [comment] 2022-11-24 08:52
I believe you still don't have the latest files if the query contains `UNIQUE (`titlelink`) ` .  That is actually using `UNIQUE KEY (titlelink(191))` in the latest version.

**Comment by acrylian** [comment] 2022-11-24 11:47
I checked and I think you may be right. We have the concept of always running all update queries so none is missed… There are earlier update queries from 1.2.4 where these titlelink indexes where introdroduce and which of course don't have the limits yet. Not sure if that is an issue on updates since these indexes already exists but on a fresh install they are for sure.

**Comment by acrylian** [comment] 2022-11-24 11:50
Furthermore these all are first dropped and then recreated so that is the issue. Generally these aold queries are never touched but in this case I have to change all those since in your case we never get to the 1.6. update ones.

**Comment by acrylian** [comment] 2022-11-24 12:09
There is a fix up now. Please test again!

**Comment by acrylian** [comment] 2022-11-24 16:16
Just tried an update and a freshinstall (fresh db) again and all worked as always. Nothing took longer than before…

**Comment by MarkRH** [comment] 2022-11-24 16:49
Here's where it ends up:

![image](https://user-images.githubusercontent.com/8035962/203834132-5aa55007-05d2-4414-9499-3331bfd62a3b.png)

This time the last green check was "user-expiry".  It seems to vary how far along it gets in this section each time.

My PHP error log ends up with:
`PHP Fatal error:  Maximum execution time of 60 seconds exceeded in \www\zentest\zp-core\functions\functions-basic.php on line 1864`

This is after I set the default database engine back to Aria.

**Comment by acrylian** [comment] 2022-11-24 17:05
That process really didn't change and there is no new stuff like the utf8mb4 conversion involved, we are already done with that at that point… I have no idea why this would now cause this depending on the db engine…

**Comment by acrylian** [comment] 2022-11-24 17:11
FYI line 1864 of functions-basic belongs to the cURL handler respectively its execution of a cURL request. That is used to set default plugin options as it always did. 

I can only assume that the Aria engine is less performant. I have no knowledge about it so perhaps we need to request Innodb tables in the end…

**Comment by MarkRH** [comment] 2022-11-24 17:11
Well I got to thinking why I kept having a time limit of 60 seconds after changing the value in PHP.INI so I did a search of the code for "60" and found 2 lines in `/zp-core/setup/index.php` and changed `@set_time_limit(60);` to `@set_time_limit(300);` and that let it complete the setup without errors and I got the License page to display with the tables using Aria.

It could be some performance issue with my PC that creating Aria tables takes just a bit longer than InnoDB. Doesn't make much sense that it would (I don't know).  Now I'm kind of curious how long I really need the timeout set for this section.

**Comment by acrylian** [comment] 2022-11-24 17:15
60 sec should actually be enough here and I personally never encountered any issue on any server/host I ever install ZP. Might be that all use innodb by default, I admit I never really checked and used the db as they create them…

It would be really weird (not to say bad) if Aria is that less performant itself… I really would like to have it work generally and of course we can raise that value in setup. But every server is different anyway…

**Comment by MarkRH** [comment] 2022-11-28 19:22
Alright.  Cool.  Yeah, my host did the update to 8.1 overnight.  For now I have configured the Galleries to use PHP 7.4.  I am slowly going through all my scripts and correcting the various warnings and errors on all my other sites.  Once I get my galleries completely working locally with 8.1, then I'll make the switch at my host.

Thanks for your work.

**Comment by acrylian** [comment] 2022-11-30 08:07
Ok, I will close this for now then.

**Closed by acrylian** 2022-11-30 08:07 UTC
