### ISSUE TITLE
Panasonic cams without GPS fix write bogus coordinates

### ISSUE THREAD

**Issue by citronalco** [zenphoto/zenphoto#1176] opened 2018-07-07 09:31 UTC
Panasonic cams without proper GPS fix write 17056881,853375 as latitude and as longitude as well.
Please ignore those coordinates.

**Comment by acrylian** [comment] 2018-07-07 09:44
"As well"? What also does this? How do you suggested we find out that the values are to be ignored? Too big numbers because the comma is missing? Sorry, I am not that into these exif things so I will probably need help here.

**Comment by citronalco** [comment] 2018-07-07 10:05
Latitude is 17056881,853375 and longitude is 17056881,853375
Here's an example: ftp://ftp.geierb.de/panasonic_gps.jpg

There are several reports on the internet about this, e.g. https://www.dpreview.com/forums/post/53877650

**Comment by acrylian** [comment] 2018-07-07 11:41
So the issue is actually the wrong comma respectively localized comma? Then this would be more or less a duplicate of #1164.

**Comment by citronalco** [comment] 2018-07-07 11:54
No, I don't think so. The issue is that, in case of no GPS fix, Panasonic writes some default values in the Exif fields instead of none.
Those default values are always the same (latitude=17056881.853375 and longitude=17056881.853375, somewhere near the north pole) and should be filtered out or ignored.

**Comment by acrylian** [comment] 2018-07-07 12:16
Ah, okay. That's weird. Still what if a photo indeed has those coordinates? I agree that might be rare as not that many people will take photos near the North pole but still these by itself are valid… 

In any case please next time write the complete info about an issue right into the ticket intially.

**Comment by kochs-online** [comment] 2018-07-12 11:36
For the sake of completeness here is what [Exiftool](https://www.sno.phy.queensu.ca/~phil/exiftool/) outputs for the given example file (description added in square brackets):
```
> exiftool.exe -g -GPS:all -a -n -n panasonic_gps.jpg
---- EXIF ----
GPS Version ID                  : 2 3 0 0   ["2.3.0.0"]
GPS Latitude Ref                : N   ["North"]
GPS Latitude                    : 17056881.853375   ["17056881 deg 51' 12.15" "]
GPS Longitude Ref               : E   ["East"]
GPS Longitude                   : 17056881.853375   ["17056881 deg 51' 12.15" "]
GPS Altitude Ref                : 0   ["Above Sea Level"]
GPS Altitude                    : 505   ["505 m"]
GPS Time Stamp                  : 00:00:00
GPS Status                      : V   ["Measurement Void"]
GPS Measure Mode                : 2   ["2-Dimensional Measurement"]
GPS Dilution Of Precision       : 0
GPS Img Direction Ref           : M   ["Magnetic North"]
GPS Img Direction               : 22.5
GPS Map Datum                   : WGS-84
GPS Processing Method           : GPS
GPS Area Information            :
GPS Date Stamp                  : 0000:00:00
```
While I can see that this is an issue, I don't think it should be fixed by the CMS. IMHO it should be part of the image workflow instead to fix the metadata before uploading/publishing the images.
Exiftool would my weapon of choice for such a task. It can be given a set of rules like `-if "$GPS:GPSStatus# eq 'V'"` (Windows syntax) or `-if "$GPS:GPSLatitude# eq 17056881.853375" -if "$GPS:GPSLongitude# eq 17056881.853375"` to match a file against and fix the problem (`-GPS:All=`).

That said I was facing a similar problem recently while building a toolchain to publish photos directly from my mobile phone to Zenphoto. In that/my use case it is intentional that there _is_ no image workflow where I could fix the messed up metadata my phone creates. So I set off to build a Zenphoto extension that would execute Exiftool argument files whenever a new image is discovered (using the `new_image` [object filter](https://www.zenphoto.org/news/zenphoto-plugin-architecture/)). This way I use Zenphoto to incorporate Exiftool into my automated tool chain while fixing metadata on file level and before it is copied to the database. (Allowing me to create proper backups of the image files as well.)
As of now I have an alpha version of that plugin that is not very thoroughly tested and hasn't seen production use yet.

**Comment by acrylian** [comment] 2018-07-12 11:49
Thanks for investigating on this quite special issue. If it is a that general know camera bug our exif lib could possibly handle this if we can be certain to  fix the right coords. 

I have never used Exiftools but it seems to be Perl library to be used via commandline? Not sure if that is generally usable on standard shared hostings then. But besides that any extension solving specific problems is welcome.

**Comment by kochs-online** [comment] 2018-07-12 12:51
> If it is a that general know camera bug our exif lib could possibly handle this if we can be certain to fix the right coords.

I'm not particularly fond of fixing metadata issues only in the database while keeping the originating file broken, but the exif lib would be an approach to handle the issue inside Zenphoto. I think it would be quite safe to use the coordinates for identification since they are so far outside any reasonable range of GPS coordinates (0-180°). Additionally the GPS Status value ("Measurement Void") could be evaluated.

> I have never used Exiftools but it seems to be Perl library to be used via commandline? Not sure if that is generally usable on standard shared hostings then.

Yes, Exiftool is written in Perl. There are executables and a library available. If run on *nix systems it requires Perl 5.004 or later. The Windows version does not require a Perl installation.
My extension runs Exiftool using [`shell_exec()`](https://php.net/manual/function.shell-exec.php) and as such cannot be used when PHP Safe Mode is enabled. I'm thinking about changing that to `popen()` or `proc_open()` to have better control over the command output (`STDOUT`/`STDERR`), but that is still work in progress and although I'm not sure I'd be surprised if that worked in Safe Mode.
As far as my experience goes chances aren't that bad to find a shared host running an OS with Perl and offering PHP without Safe Mode, but YMMV of course.

Note to self: Maybe add a check for Safe Mode and Perl version when activating the plugin.

**Comment by acrylian** [comment] 2018-07-12 13:07
> I'm not particularly fond of fixing metadata issues only in the database while keeping the originating file broken, but the exif lib would be an approach to handle the issue inside Zenphoto. 

Zenphoto "policy" is to generally not modify the original image itself. So fixing before uploading is preferred. But I think it would be pragmatic to at least fix values in the db if known. Since you already wanted to provide a fix on the other ticket, I would say include this one into your coming pull request right aways, too. 

Btw, no one should be using Safe Mode and it is gone since PHP 5.4 anyway. Actually you should not be using PHP below at least 5.6 as well ;-)

**Comment by kochs-online** [comment] 2018-07-12 13:24
> Zenphoto "policy" is to generally not modify the original image itself. So fixing before uploading is preferred.

Agreed. That's not the purpose of a CMS.

> But I think it would be pragmatic to at least fix values in the db if known. Since you already wanted to provide a fix on the other ticket, I would say include this one into your coming pull request right aways, too.

Will do.

**Comment by kochs-online** [comment] 2018-07-17 10:47
> If it is a that general know camera bug our exif lib could possibly handle this […].

Which part of the Exif lib did you have in mind? I was thinking of the maker-specific implementation (`exif/makers/panasonic.php`) since this is a Panasonic bug. What I did not realize was that these implementations are only meant for parsing the `MakerNotes` directory inside the `ExifIFD`. And even if we added that workaround to the maker-specific implementation it wouldn't work because the `MakerNotes` are positioned and parsed before the `GPS` directory. :disappointed:

If you meant the Exif lib `exif/exif.php` itself – how would you approach this problem? Parsing of the GPS data is performed by `exif/makers/gps.php`. As far as I can see this implementation is maker-independent (and should stay that way IMHO). I'm not even sure the maker info is available here at all.
Maybe we could take a look at the `GPSStatus` value and delete all GPS info if it says "_Measurement Void_". Opinions?

On a side note: I just [found out](http://www.geosetter.de/mantis/view.php?id=827) that my Sony SLT-A55V also uses the `GPSStatus` tag in the same way. The A55 however continues to use the last position recorded with a GPS fix instead of `0xFFFFFF` like Panasonic. This can be similarly annoying and there are numerous complaints by owners about this as well.

**Comment by acrylian** [comment] 2018-07-17 11:04
I was thinking indeed about the maker for panasonic but I also was not really aware that it is really only for specific "maker" info. Then if indeed the exif gps handler should do this. 

Of course we cannot catch every camera model/vendor that does store things "wrong" as that would possibly become a huge list of exceptions… And it is known that a lot do and did such things in the past, even "mis-using" fields. 

So I am not generally sure if we should catch that at all if the values itself are technically valid even if they don't make sense… But I am open to opinions of those you really use these data.

**Comment by kochs-online** [comment] 2018-07-24 17:02
How about adding a checkbox to the image options tab allowing the user to control whether to keep GPS data or not depending on the `GPSStatus` value? If this option is set `parseGPS()` will unset the GPS information if measurement is void.

**Comment by acrylian** [comment] 2018-07-24 18:44
Not sure I like an extra option for such a vendor specific issue…

**Comment by kochs-online** [comment] 2018-07-25 09:33
I don't think the underlying issue is vendor specific at all: Whenever a device is capable of adding GPS info to an image/media object, it also needs to deal with situations where no GPS coverage is available (like inside of buildings or immediately after power up). The vendors could refrain from adding GPS info at all, but then again this might not be desirable in all situations (e. g. when GPS fix is only lost for a few moments) or to differentiate between "GPS active" and "GPS inactive". For this reason the _GPS Status_ can be added to the metadata.
The question is whether a user wants to keep invalid GPS positions – remember: these could be only slightly off – or not. And I don't think there is an approach to this that generally right or wrong just like the camera vendors treat this topic differently. (Ideally this could be decided on a per file basis, but I don't see how that could be integrated elegantly.)

**Comment by acrylian** [comment] 2018-07-25 10:32
Okay, but if not enabled it should have a `null` value indicating not being set at all IMHIO. I mean what about other exif values not set? We could possibly open a can of worms if there is more of these specifics. I just want to like to avoid options only a few need but lots of users don't understand at all so we need to explain.

But again I rarely photograph and don't care about this myself so I tend to follow if you think it is useful.

>  (Ideally this could be decided on a per file basis, but I don't see how that could be integrated elegantly.)

Ideally checking the photo material before uploading would be the best way here :-) I mean if you pick what you upload don't you do that beforehand if you are a serious photographer? I mean you don't just bulk upload hundreds without checking them first. I see that the "normal non semi or full professional user" (no offence!) might do this…

**Comment by kochs-online** [comment] 2018-07-26 16:18
> Okay, but if not enabled it should have a `null` value indicating not being set at all IMHIO. I mean what about other exif values not set?

What should have a `null` value? The option? The EXIF value?
The value for `GPSStatus` **is** set in those cases I talked about. It is set to `A` ("Measurement Active") or
`V` ("Measurement Void"). Only if it is set to `V` Zenphoto needs to decide – following the option set by the user – whether to keep the GPS data or to discard it.
To help users understand that option I'd propose adding a description like "_Keep invalid GPS positions (i.e. no GPS fix) as indicated by EXIF:GPSStatus?_" or words to that effect.

> Ideally checking the photo material before uploading would be the best way here :-) I mean if you pick what you upload don't you do that beforehand if you are a serious photographer? I mean you don't just bulk upload hundreds without checking them first.

I agree with you, but the difference is: The photos we are talking about are completely fine. Even metadata-wise. The device did not have a GPS fix and correctly noted this in the metadata. Zenphoto on the other hand ignores this information and displays an incorrect geotag nevertheless.
(In Zenphoto's defense: Most tools do or don't even have support for geotags! :wink:)

**Comment by acrylian** [comment] 2018-07-26 16:38
Ah okay, thanks for clarifying.

> The value for GPSStatus is set in those cases I talked about. It is set to A ("Measurement Active") or
V ("Measurement Void"). Only if it is set to V Zenphoto needs to decide – following the option set by the user – whether to keep the GPS data or to discard it.

So if do know when these values are off, we could just silently skip it without any option, right?

**Closed** 2019-10-22 16:41 UTC
Labels: question
