### ISSUE TITLE
1.6 exif.php typeerror with Pixel4 Phone jpgs 

### ISSUE THREAD

**Issue by githlp** [zenphoto/zenphoto#1362] opened 2022-12-17 13:26 UTC
TYPEERROR: round(): Argument #1 ($num) must be of type int|float, string given in /var/www/zenphoto/zp-core/libs/exif/exif.php in line 613
```
...
612      case '9204': // ExposureBiasValue
613                $data = round(unRational($data, $type, $intel), 2) . ' EV';
...
```

My Pixel4 Phone writes this exif line
exif:ExposureBiasValue: 4/0

i guess i can rewrite exif-Info inbetween

**Comment by acrylian** [comment] 2022-12-17 13:52
The exif library has no explizit support for Pixel Phones. Sadly exif is no fixed standard and various vendors do their own thing which is why there are some handlers. We will have to review in the future anyway if some reading can be moved from thse handlers to the PHP internal exif reading which is said to be much more sufficent than in the old days.

**Comment by acrylian** [comment] 2022-12-20 16:10
We will fix the actual type issue but of course we cannot fix the actual wrong value. This is btw one of the new PHP 8.1 issue because of being more type strict.

**Comment by kochs-online** [comment] 2023-02-22 13:46
> Sadly exif is no fixed standard and various vendors do their own thing which is why there are some handlers.

This is not really true. EXIF is a well-defined standard; you can find the most recent version of the defining document in the [list of CIPA standards](https://www.cipa.jp/e/std/std-sec.html).

Most of the trouble with EXIF is caused by [device software] implementations that do not follow the standard (for lack of understanding or just giving a crap). To get an idea see Phil Harvey's (maker of the awesome tool [ExifTool](https://exiftool.org/)) rant about [Maker Note Idio(t)syncrasies](https://exiftool.org/idiosyncracies.html).

EXIF tag `0x9204` (_ExposureBiasValue_ or _ExposureCompensation_) is defined as `SRATIONAL`, meaning it consists of two signed 4-byte integers. The first integer is the numerator and the second integer is the denominator representing the rational value.

Example output by ExifTool from a random photo of mine (with ExposureCompensation 0/6):
```
ExposureCompensation = 0 (0/6)
  | |     - Tag 0x9204 (8 bytes, rational64s[1]):
  | |         02e4: 00 00 00 00 00 00 00 06
```

So my guess is for @githlp's photo `unRational()` is called with integer data `00 00 00 04 00 00 00 00` and detects a denominator of 0. To avoid division by zero the function returns the string `4/0` (which of course cannot be rounded).

To fix this I'd suggest to check the return value of `unRational()` with `is_numeric()` before trying to round it.

**Comment by acrylian** [comment] 2023-03-01 14:53
I guess we can consider this fixed now.

**Closed by acrylian** 2023-03-01 14:53 UTC
Labels: bug
