### ISSUE TITLE
Layout collapses on album page in default theme when there is no pagelist in 1.4.8

### ISSUE THREAD

**Issue by JatB** [zenphoto/zenphoto#943] opened 2015-07-08 12:29 UTC
I recently updated to the latest 1.4.8 and I noticed that the “main” and “padbox” divs now collapse on the album page for the default theme if the "thumbnails per page" option is set to more than a few thumbnails.

It looks like the cause may be that the "pagelist" div no longer shows if there are no extra album pages. Before (we were a few versions back so I’m not exactly sure when this changed) the pagelist would become 'class="pagelist disabled_nav”' if there were no more pages, keeping the layout intact. Now it simply displays nothing, causing the layout to break and collapse.

![zenphoto 1 4 8 - with and without a pagelist](https://cloud.githubusercontent.com/assets/10157440/8569986/edc91ae6-2531-11e5-9be4-16afe8085ee4.png)

**Comment by fretzl** [comment] 2015-07-08 12:39
Sorry, can't reproduce that.

Be sure you updated the themes correctly. 
For example the "default" theme does no longer exists.
It's called "basic" now.

**Comment by JatB** [comment] 2015-07-09 12:19
To try and figure out what is going on I setup a test server and installed a completely fresh install of 1.4.8. I added nine albums with test images, and you’re right, the album page was no longer collapsing on the “Basic” theme, whether the pagelist was on or off. It was, however, collapsing on all of the pages once you clicked into any of the albums. This was with a completely clean install, nothing changed or modified, everything set to default on the “Basic” theme.

The results were the same in Firefox 39.0, Chrome 43.0.2357.132 (64-bit), and Safari 7.1.7.

![gallery layout collapsing](https://cloud.githubusercontent.com/assets/10157440/8594825/9454e60c-25f9-11e5-9b3f-b209bf811586.png)

![gallery layout collapsing - more images](https://cloud.githubusercontent.com/assets/10157440/8594828/9d150218-25f9-11e5-8518-c5a848f85c5c.png)

**Comment by JatB** [comment] 2015-07-09 12:38
I think I found the issue. It looks like you’re not clearing the float on the images, but you are when you generate the albums.

At the end of the albums section:
<p style="clear: both; "></p>
</div>
</div>
<br class="clearall" />

At the end of the images section it is just closed divs. Adding a clear fixes the collapsed layout.

**Comment by fretzl** [comment] 2015-07-09 13:15
Ah, that issue has been solved a few months ago.
Please download and install the <a href="https://github.com/zenphoto/zenphoto/archive/master.zip">Support build</a>

**Comment by acrylian** [comment] 2015-07-10 10:27
Fixed in the just release 1.4.9.

**Closed by acrylian** 2015-07-10 10:27 UTC
