### ISSUE TITLE
Date formatting strftime() replacements

### ISSUE THREAD

**Issue by kochs-online** [zenphoto/zenphoto#1345] opened 2022-11-16 11:47 UTC
I'm not sure if this related to a recent update from version 1.5.4 to Master (version 1.6RC) on our site or if it already was an issue before, but I just noticed that the album date is shown wrong in the gallery. Instead of the album date the current date is shown:

![grafik](https://user-images.githubusercontent.com/17382358/202171009-5339176a-1650-4056-a984-b5cd339093f2.png)

The admin backend is showing the correct date:

![grafik](https://user-images.githubusercontent.com/17382358/202172373-dd6771e5-34b8-4efa-94b8-d8a95e077d26.png)

**Comment by acrylian** [comment] 2022-11-16 12:04
What date format have you selected? If the "locale preferred" version you might need to resave it as we have replaced internal usages of strftime(). That's deprecated in PHP 8.1 and the new have has no direct replacement so there is a workaround (which may have a bug…)

**Comment by acrylian** [comment] 2022-11-16 12:54
Yes, that oneI DId you re-save the option? We do some internal conversion from old strftime() formats to standard date formats which in tests at least did work…

**Comment by kochs-online** [comment] 2022-11-16 13:00
I set it after we fixed #1343. So that was after the upgrade.

But to be sure I just saved it again. No difference. Same result for different settings as well. The formatting is applied as selected, but always showing the current date/time for all albums. So it's not related to the format string itself or a specific album.

**Comment by acrylian** [comment] 2022-11-16 13:14
Okay, @fretzl seems to get it as well, will take a look.

**Comment by acrylian** [comment] 2022-11-16 17:27
The intl extension according to the documentation should actually do this which is why we either use its dateimmuntable class if available or the standard core datetime class…  Sadly testing is a bit off as locally with MAMP under PHP 8 getext does not work (the serverside bug also noted on our homepage)

**Comment by acrylian** [comment] 2022-11-16 17:28
You can month names in the admin because the dropdown examples are not generate date formats but static gettext strings.

**Comment by kochs-online** [comment] 2022-11-16 17:29
To clarify: I was not talking about the month names in the admin panel, but in the gallery frontend.

**Comment by acrylian** [comment] 2022-11-16 17:30
Yes, I was explained @bic-eds observation that he got the backend ones translated but not the front end ones ;-)

**Comment by acrylian** [comment] 2022-11-16 17:32
I will try on our live server soon as well.

**Comment by acrylian** [comment] 2022-11-16 17:46
For translations please also see  if this applies to your server: https://www.zenphoto.org/news/translations-gettext-not-working-on-some-servers/

Regarding the months/days I might have missed some extra steps. Dateimmuntable itself apparently does not do this… I have to use the IntDateFormatter as well… Overly complicated this stuff IMHO whie strftime() was simple…

**Comment by bic-ed** [comment] 2022-11-16 17:49
Gettext is still working on my live server

**Comment by acrylian** [comment] 2022-11-16 18:10
Gettext is working on our live server as expected, too. The months/days do not and need more work I fear. The intDateFormatter somehow uses prefedefined own formatting constants and I don't know yet how I get it to use our formats yet. But with those constants I get translated months at least. Have to dig deeper into this first.

**Comment by acrylian** [comment] 2022-11-16 18:14
![Bildschirmfoto 2022-11-16 um 19 12 24](https://user-images.githubusercontent.com/2474309/202260054-06784b85-d629-4e4b-842b-8e67c0e69605.jpg)

Actually my format was  16. August 2018 but you see the translated day name does work then…

**Comment by bic-ed** [comment] 2022-11-16 18:32
I don't see an option including day names in the select dropdown, what customized string did you use? If I try

**Comment by acrylian** [comment] 2022-11-16 18:35
No, that is not one of our date formats. It's one of the constants of intlDateFormatter class. To get what we want we apparently have to do some extra stuff as there is another date format to set patterns to that class. That then can do the month names. Overly complicated stuff for a formerly simple task…

**Comment by acrylian** [comment] 2022-11-17 13:38
I got it working, please test.

**Comment by bic-ed** [comment] 2022-11-17 14:01
I don't know, I get the translation but I don't have months in english anymore...

**Comment by acrylian** [comment] 2022-11-17 14:30
The locale aware date follows the time zone and current locale set on the server.
That is what strftime() did but not relable.

It does work on my live server:

Here set as German with German month names:
![Bildschirmfoto 2022-11-17 um 15 29 12](https://user-images.githubusercontent.com/2474309/202473109-0125d910-b7f4-4351-b40c-174e30ec1233.jpg)

Here set to English with English month names:
![Bildschirmfoto 2022-11-17 um 15 29 26](https://user-images.githubusercontent.com/2474309/202473180-4dedad10-84ac-43c8-928b-09bfee38d5fc.jpg)

**Comment by fretzl** [comment] 2022-11-17 14:41
Works for me too.

**Comment by bic-ed** [comment] 2022-11-17 15:05
I realized I had to re-run setup before testing, after that it works, forgive me :-)

**Comment by bic-ed** [comment] 2022-11-17 15:11
Anyway there is something weird with my testing server, after switching successfully a couple of times between eng and ita, it stoked to english again

**Comment by bic-ed** [comment] 2022-11-17 15:16
This is probably a persistent cache on the server side; I am not actually running the tests on my production domain, but on a subdomain.

**Comment by acrylian** [comment] 2022-11-17 15:44
Browser caches can also interfere with these things. I lost count how often did I fix CSS issues on a site although all was correct, just the browser not showing the actual status…

**Comment by acrylian** [comment] 2022-11-17 15:45
Glad it generally works.

**Comment by kochs-online** [comment] 2022-11-18 00:03
Not sure if it works as intended for me yet.

In the general options I activated German and English language settings with English as default/fallback:
![grafik](https://user-images.githubusercontent.com/17382358/202583732-ea82ca22-67ed-423b-8448-067d72e9f1f7.png)

The gallery now shows a German interface (because the user setting for my user is German), but the dates are still shown in English:
![grafik](https://user-images.githubusercontent.com/17382358/202584552-5081f01d-3e17-440c-90c4-7ce19395826f.png)

Only when I set the language default to German album dates in the gallery are shown in German.

I also tried setting the default language to "HTTP Accept Language", but it's the same result: German interface, English dates
Browser request header: `Accept-Language: de-DE,de;q=0.8,en-US;q=0.5,en;q=0.3`

(Any idea why "HTTP Accept Language" is shown with a red exclamation mark icon in the screenshot above?)

**Comment by bic-ed** [comment] 2022-11-18 07:45
Actually the whole thing is still quite weird. With my live server, when you change language the first time after a while it does the job, then the language for dates, and for dates only, somehow "persists" on the server side. I can exclude the client cache is involved, as I tested with different browsers and in any case the gettext part of translation works as expected.
It is like something switches on the server and then needs time to switch again. Asap I'll test on my local server also, even if gettext on my wamp installation does not work properly, while date translation with v5.9 are ok.

**Comment by bic-ed** [comment] 2022-11-18 07:57
More, if I change the language with one browser, lets say chrome, and then visit the site with another browser, lets say firefox, then firefox display dates in the language I set with chrome, no matter what I select in firefox. The setting lasts a few minutes, about 10 minutes I would say...

**Comment by kochs-online** [comment] 2022-11-18 08:22
> More, if I change the language with one browser […]

Just for my understanding: Which setting are you refering to exactly here? Browser setting (HTTP Accept Language), user language [of Zenphoto], active language [set], default/fallback language?

**Comment by bic-ed** [comment] 2022-11-18 08:27
> > More, if I change the language with one browser […]
> 
> Just for my understanding: Which setting are you refering to exactly here? Browser setting (HTTP Accept Language), user language [of Zenphoto], active language [set], default/fallback language?

I use HTTP Accept Language as default, with English and Italian enabled, but when I say "change settings" I mean manually change language with the dynamic locale plugin switcher (flags; no subdomains)

**Comment by acrylian** [comment] 2022-11-18 08:49
I can sort of reproduce it. The translateed months only work if you change the main language on the backend options. But not if you select a language on the frontend. Something interferes here. I will take a look on Monday as I am out of office over the weekend.

**Comment by bic-ed** [comment] 2022-11-18 08:52
Thanks acrylian, I'd be glad to help, but I'm afraid it's beyond my knowledge all of this new date thing ;-)

**Comment by acrylian** [comment] 2022-11-18 09:01
Think I know what it is. Using the site locale constant instead of the current user locale.... But more on Monday.--Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 18.11.22, 09:52 schrieb bic-ed ***@***.***>:

   
  Thanks acrylian, I'd be glad to help, but I'm afraid it's beyond my knowledge all of this new date thing ;-)

**Comment by bic-ed** [comment] 2022-11-18 10:19
You guessed right, tweaking with the SITE_LOCALE constant, in functions-i18n.php, I was able to make things work, but I won't touch anything since it is used in admin-options.php as well but with a different purpose I guess. Have a nice week-end!

**Comment by acrylian** [comment] 2022-11-18 16:14
We have a constant for the user locale, too  Will fix that next week--Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 18.11.22, 11:20 schrieb bic-ed ***@***.***>:

   
  You guessed right, tweaking with the SITE_LOCALE constant, in functions-i18n.php, I was able to make things work, but I won't touch anything since it is used in admin-options.php as well but with a different purpose I guess. Have a nice week-end!

**Comment by acrylian** [comment] 2022-11-21 12:54
There is a fix now, please test!

**Comment by acrylian** [comment] 2022-11-21 14:09
FYI, it works on our live server as intended.

**Comment by bic-ed** [comment] 2022-11-21 15:33
I've just tested and it works for me too, but I'm still facing some minor issues (not related with localization) if I use some formatting parameters in zpFormattedDate(). For instance, with **_j_** or **_i_** the date output stops as soon as they are encountered in the formatting string. Can you reproduce this issue?

**Comment by acrylian** [comment] 2022-11-21 15:57
I can reproduce this somehow. No idea what happens here and nothing in the debuglog.

**Comment by bic-ed** [comment] 2022-11-21 15:58
Nothing in the log sadly, anyway j and i are existing parameters:

> j - The day of the month without leading zeros (1 to 31)
> i - Minutes with leading zeros (00 to 59)

Weirdly if you use `**d**` instead of j you get the behavior of j

**Comment by acrylian** [comment] 2022-11-21 16:01
Yeah, I just noticed that some formats don't look as they should and that time formatting is off. Have to do more test. Either this is a PHP bug itself or some detail is wrong somewhere… Don't think it is our internal conversion since ther strftime formats always have a leading %.

**Comment by bic-ed** [comment] 2022-11-21 16:03
No, I can say it's not the internal conversion at all, because I'm testing the date parameters directly.

**Comment by bic-ed** [comment] 2022-11-21 16:57
Jes I known, but not if you use the new parameters directly, am I wrong?

**Comment by acrylian** [comment] 2022-11-21 17:00
It will always go through the conversion method even if there is nothing to convert… Except the % sign there is no actual way to guess if this is a strftime() format or just an additional char (no idea why but technically you can use a date format with a % sign ;-)).

**Comment by acrylian** [comment] 2022-11-21 17:01
>  (no idea why but technically you can use a date format with a % sign ;-)).

I mean an extra char like that or others. I could check if a string includes a % char and then only do the converions. But actually without nothing "should" happen.

**Comment by acrylian** [comment] 2022-11-21 17:01
I am re-opening this with a bit different ticket title…

**Comment by acrylian** [comment] 2022-11-21 17:45
I know what it is. It is the 2nd conversion if we request short or full month/day names. Since that is another dataformat time and such are also different. Did I mention I love the consistency of PHP so we have to handle with three different format? ;)

**Comment by acrylian** [comment] 2022-11-21 17:54
I committed a quick fix.

**Comment by bic-ed** [comment] 2022-11-21 18:34
> Did I mention I love the consistency of PHP so we have to handle with three different formats? ;)

Quite crazy indeed :-)
Sadly is not working on my local server. I'm on windows though, that could be os related. I get printed some weird strings like:
`Format: d F Y - Format-intl: d MMMM Y – 17 September 2022` 
Later I'll test on live server also
:-(

**Comment by acrylian** [comment] 2022-11-21 18:47
It's actually correct if you look at the last part. I rushed the commit and  just forgot to remove some debug code ;-)

**Comment by acrylian** [comment] 2022-11-21 18:49
Please try again, I removed it…

**Comment by bic-ed** [comment] 2022-11-21 19:16
Ah ok! Actually it seems fine now, though for some reason the parameter `d` is outputting what is expected from `j` . But that's a minor issue imho.

**Comment by acrylian** [comment] 2022-11-21 19:48
Ah, I see, besides there being a bug there were missing conversions:

- d => dd (with leading zero)
- j => d (without leading zero)

Order is quite important to not replace already replaced ones…

Please test around…

**Comment by bic-ed** [comment] 2022-11-21 22:05
Yes, it's ok now!

**Comment by kochs-online** [comment] 2022-11-23 07:22
Sorry to be the party pooper, but I think it's still not working completely:
Using "HTTP Accept Language" as language setting in general options, "de-DE" as browser setting and English as user setting I get a mix of languages:
![grafik](https://user-images.githubusercontent.com/17382358/203491200-4e46377e-3f4f-4ade-9d50-460920755434.png)

**Comment by acrylian** [comment] 2022-11-23 08:41
We'll try to find out.

**Comment by acrylian** [comment] 2022-11-23 18:01
I can reproduce the issue. http accept is not involved actually. The user language choice somehow partly overrides the manual frontend selection. In a private window being logged out everything works as expected though. Not sure how that partly override happens yet.

**Comment by acrylian** [comment] 2022-11-23 19:28
I think I fixed it.

**Closed** 2022-12-13 18:37 UTC
