### ISSUE TITLE
openstreetmap.php is ignoring settings on image.php and zooming the map out to almost maximum

### ISSUE THREAD

**Issue by JesseHC** [zenphoto/zenphoto#1417] opened 2024-03-26 12:52 UTC
On album.php, openstreetmap.php loads the map correctly. On image.php, it ignores the plugin settings and loads the map almost fully zoomed out.

I’m not sure if this is it, but on line 714 of openstreetmap.php `single-cluster`, which is used on image.php, looks like it is defined differently than `cluster` and `single`.

Tried enabling and disabling the *Show album markers* setting, since it seems to determine if `single-cluster` or `single` is used for image.php, but it didn't make a difference.

**Comment by JesseHC** [comment] 2024-03-26 12:57
Not sure if you want this here, or as a separate bug, but I noticed that if an image has description text, that an extra ***\n*** is put at the start and end of each line in the image popup on the map.

**Comment by acrylian** [comment] 2024-03-26 14:31
The clusters are for albums only to group several nearby markers actually. We'll look into that.

**Comment by acrylian** [comment] 2024-04-07 16:46
Sorry for the quite late reply. I am not sure I can reproduce this. The map on the single image uses the "Map zoom" value testing with the Zenpage theme as intended. That is 4 on my setting and is quite zoomed out with 1 being the most zoomed out level.

**Comment by JesseHC** [comment] 2024-04-18 09:10
Yeah, you’re right. I thought that the default zoom level of 4 meant it was quite zoomed in, though when I [looked in to it](https://wiki.openstreetmap.org/wiki/Zoom_levels), it is actually, like you said, zoomed almost all the way out. Changing the map zoom setting fixed the image page issue for me.

So the issue is actually that the zoom level for the cluster on the map for album.php is ignoring the map zoom level setting when the cluster area is limited. You can test this by putting one geotagged image (or multiple images if they were tagged in the same area) in an album.

This is how the map will look on the album page-
![openstreetmap-album](https://github.com/zenphoto/zenphoto/assets/82089671/49eacde7-5e71-4b3f-889c-c655231f761b)


This is how it will look on the image page with a default zoom setting of 4-
![openstreetmap-image-map-zoom-4](https://github.com/zenphoto/zenphoto/assets/82089671/8e569593-7b42-4a24-8fa1-6a852d25bebc)


Finally, here’s how the image page will look with the zoom setting changed to 18-
![openstreetmap-image-map-zoom-18](https://github.com/zenphoto/zenphoto/assets/82089671/ce0f48d8-cdb1-43c0-9fbd-43b99137c1dc)


So this is mostly a non-issue, and you can close this if you’d like.

It would still be nice if the extra \n being added for each line with the description text was fixed on the cluster pop-up windows. I just noticed that it wasn't happening on my local MAMP test server, but it was happening on my live server.

![extra n](https://github.com/zenphoto/zenphoto/assets/82089671/9c165a45-2421-41af-8848-2956577525ab)

Thanks!

**Comment by JesseHC** [comment] 2024-04-18 09:47
I think I got an idea how to duplicate the \n issue in the cluster pop-up, and it is also happening locally on my MAMP test server.

Description metadata with carriage returns isn’t being recognized by Zenphoto. It all gets changed to one long line of text when it is read in. If you manually add the paragraph returns back in the Description field under the Images tab, in this case using TinyMCE 4.x, and then apply the changes, the extra \n gets added to the map.

In this example, if you look at the source, after adding the paragraphs back it will now look like this-
![Description Source code](https://github.com/zenphoto/zenphoto/assets/82089671/e9e2d16f-c16a-45d3-8a37-c9187d7c4988)

The map cluster pop-up will now be filled with extra \n all over the place-
![extra n all over the place](https://github.com/zenphoto/zenphoto/assets/82089671/7dcb8888-54c8-414f-b1f6-dcd9ea95650c)

**Comment by acrylian** [comment] 2024-04-18 13:57
Btw, the \n appearance seems not happen if the description is not truncated. 

> Description metadata with carriage returns isn’t being recognized by Zenphoto. It all gets changed to one long line of text when it is read in. 

Actually there is an option for that on Options > Image:
![Bildschirmfoto 2024-04-18 um 15 54 36](https://github.com/zenphoto/zenphoto/assets/2474309/c413edec-3271-4efc-a797-4795336d57b6)

**Comment by JesseHC** [comment] 2024-04-20 06:28
> Actually there is an option for that on Options > Image:
> ![Bildschirmfoto 2024-04-18 um 15 54 36](https://private-user-images.githubusercontent.com/2474309/323632192-c413edec-3271-4efc-a797-4795336d57b6.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1OTM5MzYsIm5iZiI6MTcxMzU5MzYzNiwicGF0aCI6Ii8yNDc0MzA5LzMyMzYzMjE5Mi1jNDEzZWRlYy0zMjcxLTRlZmMtYTc5Ny00Nzk1MzM2ZDU3YjYuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjBUMDYxMzU2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTYwNmFhNmU4MTEzNzU0NjcwZWNiZTg5MzQ4NzgzN2ExODhhY2FiZWY5ZTg4NmZiYmEyZjM3ZGRkNDY0OTFlZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.-ML7RIqiQt3wR_XClmffZJSIu-ZIcAlDogjkqgX5uYs)

I tried turning that on, and when I refresh the metadata, it doesn’t convert any line breaks to `<br>`, it is still all one line.

![linebreaks option turned on](https://github.com/zenphoto/zenphoto/assets/82089671/3dc219bc-0632-4b21-b179-810bace551f9)

![Source code with linebreak br option](https://github.com/zenphoto/zenphoto/assets/82089671/90ae2803-d6b9-40bb-adbf-00f9bd8fd4c1)

While we are on the topic, in the actual Image Caption metadata displayed, all of the line breaks show up as `&#xA;` and there is no way to remove them. They also show on the image page under Image Info, if selected, which is unfortunate.

![Image caption metadata](https://github.com/zenphoto/zenphoto/assets/82089671/852136d2-9760-4fa5-a5fe-9eb7b4874113)

**Comment by acrylian** [comment] 2024-04-20 08:55
The line breaks are converted on importing via the native PHP function: https://www.php.net/manual/en/function.nl2br.php

It only applies to the IPTCImageCaption field as the ExifDescription is considered the title if there is no IPTCObjectName field set. Have to try it myself.

![Bildschirmfoto 2024-04-20 um 10 47 25](https://github.com/zenphoto/zenphoto/assets/2474309/bb928978-eaa1-482b-9b90-8b558908ee89)

Since `&#xA;` is a HTML encoded linefeed character that likey happeens as  we eof course html_encode output generally for metadata within the metadata table.
![Bildschirmfoto 2024-04-20 um 10 54 51](https://github.com/zenphoto/zenphoto/assets/2474309/be0df51e-3bbb-4dcc-b7ee-0c490ff12f1f)

**Comment by acrylian** [comment] 2024-04-21 11:55
I tested a bit around and the `&#xA;` html encoded line breaks happen on importing. I assume this is an issue of metadata encoding in the image somehow. 

My test image didn't set anything apparently so ZP assumed utf-8 so this is there directly after importing.  I first thought our image class method `prepIPTCString()` doing the encoding conversion might cause it but it is even there if I bypass that. 

Therefore the php native `nl2br()`  naturally fails converting linebreaks as there are no "linebreaks" anymore. Using `html_decode()` before `nl2br()` tdoes work as intended. I have committed that fix for now. (it does not help anything with the \n in the map description.)

**Comment by acrylian** [comment] 2024-04-24 08:28
I believe I found the fix for the unwanted visible line breaks. Fix is up in 1.6.3a now.

**Comment by JesseHC** [comment] 2024-04-25 08:48
The \n did disappear from the map cluster popups, so thank you for that.

There are still multiple issues I’m experiencing with line breaks in the image description.

* First, if you add an image with line breaks in the description, or refresh metadata on an image with manually added paragraphs in Zenphoto, the description will lose all line breaks and show up as one long string of text.

* In Metadata\Image Info, `&#xA;` does not show in the _Image Title_ field where there are line breaks, but it is still showing in _Image Caption_. Both fields display as one long line of text, and do not show any actual line breaks. Looking through the actual database, you can see that `&#xA;` does not show up in _EXIFDescription_, but it does in _IPTCImageCaption_.

* One other issue noticed with the _Image Caption_ field, is that if you refresh metadata on an image where the description was previously formatted in Zenphoto, and exported to an XMP sidecar file using the xmpMetadata's plugin option _Export metadata info to XMP sidecar_, the html formatting read from the XMP file will be displayed in _Image Caption_.

**Comment by JesseHC** [comment] 2024-04-25 09:01
I can tell you that the description paragraphs were added originally in Adobe Lightroom, but they have displayed correctly in most image viewers I have tested them in.

* In Adobe Bridge *(no surprise there)* the paragraphs are shown in 
	* IPTC Core - Description
	* Camera Data (Exif) - Image Description

* In Preview correctly under IPTC - Caption/Description.

* In Xee<sup>3</sup> paragraphs are shown in 
	* IPTC properties - Caption-Abstract
	* EXIF properties - Image Description
	* XMP properties - Description

* XnView MP 1.7.1 paragraphs displayed as correct under EXIF - Camera - Image description, but displayed as one line in:

	* IPTC-IIM -
		* Caption - Caption
	
	* ExifTool -
		* EXIF - Image Description
		* IPTC - Caption-Abstract
		* XMP - Description
	
	* and cutoff in XMP - dc - description.

* digiKam 7.9.0 displayed all properties as one line.

**Comment by acrylian** [comment] 2024-04-25 09:46
Could you please move this to a new ticket about image meta data?

**Comment by JesseHC** [comment] 2024-04-25 10:23
I agree with you, things were starting to spiral off topic. I actually wrote up the issue last year but never posted it. So now it's been posted.

**Comment by acrylian** [comment] 2024-04-25 10:31
Thanks, I will close this as its issue is fixed

**Closed by acrylian** 2024-04-25 10:31 UTC
Labels: question, works for me, under investigation
