### ISSUE TITLE
Dates and times in RSS feeds failing or wrong in 1.6

### ISSUE THREAD

**Issue by JesseHC** [zenphoto/zenphoto#1363] opened 2022-12-18 05:57 UTC
Going through my gallery’s main RSS feed I noticed that the dates were wrong or failing for the date and time under the title, as part of the `<description>`, and the date and time under the thumbnail, as part of `<pubDate>`.

When looking through the other album RSS feeds, it was mostly an issue with video files, though it also happened on images. The issue was all over the place, maybe half the video files would show it, and some of the images. If it was a problem reading the file’s date, that doesn’t seem like it should affect the publication date?

In the screenshot I’ve included, you can see that the first entry fails with the description date, defaulting to _Wed, 31 Dec 1969 16:00:00 -0800_, but has the correct publication date. The next entry fails on both, but with the publication date being random and not 1969. Then the next has the correct description date but incorrect publication date, again not 1969.

![RSS dates and times wrong in both spots](https://user-images.githubusercontent.com/82089671/208283651-ae28d8b9-6ced-4135-8fee-14b5f21fabf2.png)

I’ve tried deleting the RSS cache and changing the RSS plugin settings multiple times. The files in the example image were uploaded before the upgrade to 1.6, but I also tried it on a new batch of files and it was still having the issue.

**Comment by acrylian** [comment] 2022-12-18 09:15
Will try to reproduce. If you get a date like 1969 that means either there is no valid date string (which you of course exclude). 

- pubDate: uses the date field of the image or album (the one you can enter on the backend). There I see a probably forgotten update regarding the new date formatting required in 8.1 (I think there is even preformatted constant for RSS required formatting).  But neverthess this actually should display correctly if the date string is correct… Can you post an example please?
- The date within description uses the mtime which is usually a time string. It uses the correct formatting function and if there is a valid tiimestamp it should display correctly. This uses the date format defined on the backend. What format have you set and also can you please post a failing ?

**Comment by JesseHC** [comment] 2023-01-06 12:10
The one thing I have noticed is that most of the files having the issues, though not all, are not from digital cameras; meaning screenshots, scanned images, and animated GIFs, along with video files. Things that might have different metadata than images with EXIF info from a digital camera. So maybe this makes it less of a priority, or gives you an area to focus on.

Looking through the subalbums with issues in admin, the Date is empty on each one with a publication problem (which I guess makes sense, though I don’t know why they are empty).

The Date format was set to Custom and the entry was _locale_preferreddate_notime_ under Options-General. I believe I have never touched that before the update to 1.6. I’ve tried changing it to different options, but it didn’t help.

This is the results when I tried some other date formats. The formats were inconsistent in how they were displayed between the `<description>` and `<pubDate>`, with the `<description>` not honoring the preference (those shown here were from working entries)-

_Custom: locale_preferreddate_notime_
> `<description>`
> May 22, 2022 at 6:58 AM
> 
> `<pubDate>`
> Date: 5/22/22


_Preferred date representation_
> `<description>`
> January 24, 2016 at 2:09 PM
> 
> `<pubDate>`
> Date: 2/5/16, 9:53 AM


_February 15, 2008 1530_
> `<description>`
> April 3, 2016 at 12:31 AM
> `
> <pubDate>`
> Date: April 04, 2016 10:40


I’ve been trying to look through my files to find where the issue is consistently happening, but it seems to be all over the place (meaning it will happen to some videos but not other in the same batch). If I find anything else, I’ll let you know. If you would like me to provide example files that it is happening to, I can also try to do that, just let me know where you would like them sent.

**Comment by JesseHC** [comment] 2023-01-06 12:11
Going through the files, one request I have is that you please replace in the RSS feed at the end of the RSS title that says “(latest images)” with “(latest entries)” and the “Image Info” button on the image page with “File Info” or “File Properties”, since there can also be videos and audio files in Zenphoto.

Thanks!

**Comment by acrylian** [comment] 2023-01-06 13:05
Perhaps it is a PHP bug since the dates are locale aware and so add up time zone info and cause wrong dates… I have no idea. Note that both entries (may) use different dates (mtime vs db/file meta date if they are not the same).

> Going through the files, one request I have is that you please replace in the RSS feed at the end of the RSS title that says “(latest images)” with “(latest entries)” 

That makes sense actually.

>  the “Image Info” button on the image page with “File Info” or “File Properties”, since there can also be videos and audio files in Zenphoto

Make sense. We could also check if it is an image to internally switcht. But a general term is probably good anyway. You don't have to wait until any update: `printImageMeta()` has a parameter title to override that button text.

**Comment by JesseHC** [comment] 2023-03-17 14:06
I replied on the other bug report, but it also did not fix this issue for me.

After installing the latest 1.6.1 alpha and running setup, I went into the latest folder of images I had tried in 1.6. It only had eleven images, but three had blank dates and one had a date set to the next month in the images tab for the album. These images also had xmp sidecar files that had location and people tags. I tried updating the Metadata for the album and individual images with problems, but it did not fix any of the date issues.

Setting the Date format in Options-General from the previous Custom to a specific format did not fix the image date problems; by itself, or by refreshing the metadata.

Same goes for setting it to use the localized date.

The one image with the wrong date, had it set a month later than the rest-
> Date: 2023-02-04 06:02:08

Under General for that image it had it as _Last change: 2023-01-11 01:57:39_

The previous image in the batch was:
> Date: 2023-01-04 06:01:54

and had the same Last change date and time (_2023-01-11 01:57:39_).

The interesting thing is that all of the images are from the same batch, all have similar metadata in the images themselves, and in the xmp files.

This was tested locally in MAMP running 7.4.12, 7.4.33, and 8.2.0.

Also tried switching the graphics library from Imagick to GDlibrary, to see if that would make a difference since a [forum post](https://forum.zenphoto.org/discussion/1411085/date-not-being-added-to-uploaded-images-in-1-6) thought it might, but that did nothing.

For the RSS files, the `<description>` date and time did not change on them. Many are still set to _Wed, 31 Dec 1969 16:00:00 -0800_, and for those working, something like _June 23, 2013 at 5:02 AM_.

The `<pubDate>`, like before, did change depending on the setting in Options-General-Date format.

1.6 with the old Custom value of locale_preferreddate_time:
> Date: 2013-06-23

1.6.1 with Date format set and time added (but localized date not turned on):
> Date: June 23, 2013 5:02 AM

1.6.1 with localized date also set:
> Date: June 23, 2013 12:02 PM

**Comment by acrylian** [comment] 2023-03-17 14:55
GD or Imagick have nothing to do with all this. My answer on the other ticket applies here as well of course ;-)

**Comment by acrylian** [comment] 2023-03-18 17:37
As mentioned on #1359 thte RSS as well uses the mtime and not the metadata Time Created. 

![Bildschirmfoto 2023-03-18 um 18 23 00](https://user-images.githubusercontent.com/2474309/226123310-826d2e7b-0aca-405d-ad0e-61a3486ccece.jpg)

That date is correct because i downloaded the image yesterday. Why we do this I don't remmeber but it is also not new.

 ----

>1.6 with the old Custom value of locale_preferreddate_time:
>Date: 2013-06-23

In 1.6.1a you need to proved a ICU dateformat if using a custom date and localized dates. This is new and sadly must be that way because of inclompatible formats we cannot savely convert. See the updated option text of the also reworked option.

> 1.6.1 with Date format set and time added (but localized date not turned on):
> Date: June 23, 2013 5:02 AM

> 1.6.1 with localized date also set:
> Date: June 23, 2013 12:02 PM

Note that localized dates not only refers to auto translated day and months names (no gettext involved or so, that's core PHP) but also timezones. That means the date may also calculated based on your time zone setting.

**Comment by JesseHC** [comment] 2023-03-20 02:36
I guess the biggest problem I’m having is that many of the files that are being added no longer show a date in the latest version of Zenphoto, the entry is completely blank. Or if they do have a date, it might be a wrong date that is not based on the mtime or any metadata.

This wasn’t a problem until recently.

For the `<description>`, it might make sense to have a fallback that uses mtime, instead of showing _“Wed, 31 Dec 1969 16:00:00 -0800”_ as it currently does if there is no date, even though that doesn’t actually solve the problem.

It also makes sense to have the `<pubDate>` set to mtime, especially for an RSS entry. It might help clear things up for the user if the _“Date:”_ text was changed to _“Data added:”_.

Though, as shown in my first screen shot, mtime wasn’t the real problem with the `<pubDate>` entry. The problem was that the dates were completely wrong. Two of the three entries had 1937 and 1944 for their dates, when all of them should have shown something in 2022.

**Comment by acrylian** [comment] 2023-03-20 08:04
I don't think I can reproduce your problems. I don't get any wrong dates. We actually didn't change anything regarding reading metadata from images. Just the formatting to display them was changed.

Please send some images with the issue(s) so we can actually test them.

**Comment by JesseHC** [comment] 2023-03-24 08:52
Most of the issues with blank dates in Zenphoto are coming from images or videos that don’t necessarily have date and time info in EXIF, IPTC, or XMP metadata fields, but like any file, they do have Creation date and a Modification date set in the file properties. So if the date and time cannot be pulled from extra metadata, Zenphoto should at least be using the Creation date instead of leaving blank dates.

Since I’ve seen other people having this issue on the forum, and don’t want to make it seem like it is my images only having the issue, I’ve linked to sample images online that will show you what I mean.

They will all display blank dates in the Images tab, and will then default to the 1969 description date in the RSS feeds.

**GIFs**
Here’s an example image from the [Wikipedia entry](https://en.wikipedia.org/wiki/GIF)-

https://en.wikipedia.org/wiki/GIF#/media/File:Sunflower_as_gif_websafe.gif

**Animated GIFs**
Same goes for animated GIFs.

https://en.wikipedia.org/wiki/GIF#/media/File:Newtons_cradle_animation_book_2.gif

**PNG**
From the [Wiki entry](https://en.wikipedia.org/wiki/PNG).

https://en.wikipedia.org/wiki/PNG#/media/File:PNG_transparency_demonstration_1.png

**JPEG**
A JPEG from a digital camera exported in Photoshop Save for Web with metadata turned off (there are a few options for this), and many other image editors will do this. I've attached a personal image for you to check out.
![PS_Save_for_Web](https://user-images.githubusercontent.com/82089671/227470593-ce0765fa-d7a8-495b-b539-f9357e76d2a9.jpg)


**Screenshots**
From the [Wiki](https://en.wikipedia.org/wiki/Screenshot).

This one also has Modify Date, Datecreate, and Datemodify in the PNG properties, but shows nothing extra.
https://en.wikipedia.org/wiki/Screenshot#/media/File:QEMU_6.2_screenshot_(cropped).png

**Scanned images**
From [here](https://www.scanmyphotos.com/samplescans.html).

Even this example has Modify Date in EXIF properties and Modify Date and Metadata Date in XMP properties and doesn’t work.
https://www.scanmyphotos.com/images/samplescans/300DpiSample.jpg

**MP4 video files**
From [here](https://samplelib.com/sample-mp4.html).

https://download.samplelib.com/mp4/sample-5s.mp4


All images have a blank date.
![All have blank Dates](https://user-images.githubusercontent.com/82089671/227470730-b03139cd-f26b-403c-b44f-c0bc51dc1aa4.png)

_(Realized this post should really go here because it is about blank dates, even though there is crossover with most of my date issues with files right now in Zenphoto.)_

**Comment by acrylian** [comment] 2023-03-24 08:56
> Realized this post should really go here because it is about blank dates, even though there is crossover with most of my date issues with files right now in Zenphoto.)

We should actually have just one date ticket in the first place as all is possibly connected ;-) Thanks for the images, I will try to reproduce it.

**Comment by JesseHC** [comment] 2023-03-24 08:58
All description dates in the RSS feed will then be the default 1969 because the dates are blank in Zenphoto.

![Blank description dates 1969](https://user-images.githubusercontent.com/82089671/227471985-6301707a-aab3-426d-96e2-85037a03060f.png)

If you want me to find sample files that are generating wrong or random `<pubDate>` entries, I can try to dig around for that.

**Comment by acrylian** [comment] 2023-03-24 09:05
That makes sense if there is no date. Do you actually have the related meta data fields enabled for import? If not they are of course not imported. If then not the mtime is used is then surely a bug to investigate.

**Comment by acrylian** [comment] 2023-03-24 09:27
Okay, good. It's just that we recently  stumbled upon that and then realized that of course with a disabled field there is also no value ;-)

**Comment by acrylian** [comment] 2023-03-24 09:44
I did download those images and I am afraid I cannot reproduce it… I get proper upload dates on all and also in RSS:

![Screenshot 2023-03-24 at 10-36-44 zenphoto-dev admin albums-imageinfo](https://user-images.githubusercontent.com/2474309/227484083-032a8b92-3325-40f5-9e9d-28f1339397e6.png)


![Bildschirmfoto 2023-03-24 um 10 37 10](https://user-images.githubusercontent.com/2474309/227484190-179e44dc-9df8-4042-b1fa-b38f42e734cb.jpg)
![Bildschirmfoto 2023-03-24 um 10 37 14](https://user-images.githubusercontent.com/2474309/227484197-b1beb930-577f-42a7-bd93-f85674350313.jpg)
![Bildschirmfoto 2023-03-24 um 10 37 18](https://user-images.githubusercontent.com/2474309/227484199-42ab194f-3f18-441a-9aca-990431ffea27.jpg)
![Bildschirmfoto 2023-03-24 um 10 37 21](https://user-images.githubusercontent.com/2474309/227484204-0a992539-75dd-4498-9829-bc12131191f1.jpg)
![Bildschirmfoto 2023-03-24 um 10 37 26](https://user-images.githubusercontent.com/2474309/227484208-1344aae1-4f90-4660-a81a-d1797e294b0e.jpg)
![Bildschirmfoto 2023-03-24 um 10 37 30](https://user-images.githubusercontent.com/2474309/227484213-b1414012-96e9-4d26-94af-d15e1d61813d.jpg)

And it is not my RSS client adding that date somehow, it is in the feed itself:

![Bildschirmfoto 2023-03-24 um 10 44 13](https://user-images.githubusercontent.com/2474309/227484502-49b1fdd5-6217-421f-8241-b9595baff0df.jpg)

**Comment by acrylian** [comment] 2023-03-24 09:45
There are no metadata entries for dates since there are none.

**Comment by JesseHC** [comment] 2023-03-24 10:03
I should add that my local test server is using PHP 8.2.0 in MAMP 6.8.

My live server is using PHP 7.4.33 (which I can’t change, and my hosting company this week has said will be upgraded sometime “later this year”).

**Comment by JesseHC** [comment] 2023-03-24 10:16
> There are no metadata entries for dates since there are none.

As mentioned, the scanned sample 300DpiSample.jpg had the following metadata for dates:

**EXIF properties:**
Modify Date: March 7, 2012 at 10:27:13 AM PST


**XMP properties:**
Create Date: 1903:12:31 16:00-08:00
Modify Date: March 7, 2012 at 10:27:13 AM PST
Metadata Date: March 7, 2012 at 10:27:13 AM PST


The screenshot QEMU_6.2_screenshot_(cropped).png had the following under **PNG properties**:
Modify Date: March 24, 2022 at 3:49:32 PM PDT
Datecreate: 2022-03-24T15:49:32+00:00
Datemodify: 2022-03-24T15:49:32+00:00

**Comment by fretzl** [comment] 2023-03-24 11:30
I tested the example images too and get the same results as @acrylian.

**Comment by acrylian** [comment] 2023-04-02 11:47
Closing this as it appears to be working for us in tests. If still something is wrong, please create a new general "date format issue" ticket. as this is the same "issue area" like #1359 which I also will close now.

**Closed by acrylian** 2023-04-02 11:47 UTC
Labels: under investigation
