### ISSUE TITLE
Comments: unable to enter emojis in comments

### ISSUE THREAD

**Issue by viktorzen** [zenphoto/zenphoto#1257] opened 2019-12-19 15:47 UTC
Hello, another emoji issue, if I enter an UTF8 emoji directly (via the Windows + . emoji input box) in a comment, it is somehow stripped away both in the admin comments panel and on the zenphoto page. Why is this happening?

**Comment by acrylian** [comment] 2019-12-19 17:30
Because of the database encoding utf-8 Zenphoto currently uses which does not support these multibyte characters. This is on the list as it required some database changes that need testing we didn't get around yet (shame on us). It might not get into 1.5.x anymore. I will close it as it is basically a duplicate of #1094

**Closed by acrylian** 2019-12-19 17:30 UTC
Labels: duplicate

**Comment by viktorzen** [comment] 2019-12-19 18:04
ok thx, I have seen that the database tables are already set to utf8, so I don't think this can be such big of a deal. Not sure where these characters get filtered out,  because in the admin panel emjois in news articles are actually stored and displayed correctly.

**Comment by acrylian** [comment] 2019-12-19 18:16
Sadly it is not that simple. It is not Zenphoto filtering these and utf8 as the database encoding is not supporting and the database is simply not storing these. That is the issue. You need to convert your database to `utf8mb4_unicode_ci`  (MySQL 5.5.3+) or `utf8mb4_unicode_520_ci` (MySQL 5.6+). Sadly this is not just a simple conversion like Western encoding to Utf8. You might loose content respectively get it truncated if the sizes of text fields itself are not adjusted, some fields actually need to get larger as a single character then requires 4 bytes instead of 3 for storage. This needs testing as setup should handle that correctly and possible even other changes. 

You can try to change your databse but on your own risk it has not been tested with Zenphoto and don't forget a database backup. Don't do this on an important live site.

**Comment by viktorzen** [comment] 2019-12-19 22:33
I have done some quick research and found out that the utf8 encoding of mysql is also already a mulitbyte encoding, but that stores only max 3 bytes instead of the full 4 bytes as utf8mb4:

https://stackoverflow.com/questions/30074492/what-is-the-difference-between-utf8mb4-and-utf8-charsets-in-mysql

I think changing the table and fields to utf8mb4 should work, but I am not sure whether there is still another problem maybe with the multi-lingual serialization zenphoto does. I would like to see the serialization removed, if you are using only one language (multi-lingual disabled in zenphoto). would make things much cleaner in the database and easier manageable if you are using only one language.

support of Emojis and full unicode utf8 support should be a priority in my opinion, because this is really needed nowadays.

**Comment by acrylian** [comment] 2019-12-20 09:16
>  but that stores only max 3 bytes instead of the full 4 bytes as utf8mb4:
Which I bascially told above ;-)


> I would like to see the serialization removed, if you are using only one language (multi-lingual disabled in zenphoto). would make things much cleaner in the database and easier manageable if you are using only one language.

This is not going to happen as we explained several times in the past. It is always serialized as you otherwise would loose content if you disable multilingual. Abandoning the serlialization concept for languages would be to have one field per language. Which would make item entries quite inconvenient, so it would probably be one item entry per language or better a separate table for just the content fields. This is by no means makes the database easier to handle - you don't need to directly handle this and serialization is not complicate and for the db it does not make any difference - as you have to deal with several connected tables. Besides this requires changes in lots of places. I don't not think this is necessary.

**Comment by acrylian** [comment] 2019-12-20 09:53
Regardless I decided to move this up the list now.

**Comment by viktorzen** [comment] 2019-12-20 18:31
## serialization ##
thx for the update, I see the points, with the serialization it is hard to replace text on the database level, because serialization is not a native function of mysql, maybe a utility on the admin panel to replace text in the database (news articles, descriptions, etc) would mitigate the need to go to the database

## utf8mb4 ##
utf8mb4_unicode_ci is still a variable-length utf8 encoding, meaning that not every character needs the full 4 bytes. In fact, I still think converting to utf8mb4 from utf8 (mysql) should not be such a big deal, because it would not alter the length of exiting strings, but would allow to properly encode emojis and other unicode characters above U+FFFF properly. utf8_unicode_ci and more so utf8_general_ci are just outdated types of mysql that should not be used any more in my opinion.

**Comment by acrylian** [comment] 2019-12-20 19:05
> serialization
You can easily use tools like phpMyAdmin if you really need to replace something and the admin backend for changing database values "is" the admin backend tool. Otherwise there are lots of functions and methods to do this via code. You should not really change db values directly anyway becasue there might be relations.

> utf8mb4
Not so sure. From the official MySQL doc (https://dev.mysql.com/doc/refman/5.5/en/charset-unicode-conversion.html):

> A TINYTEXT column can hold up to 255 bytes, so it can hold up to 85 3-byte or 63 4-byte characters. Suppose that you have a TINYTEXT column that uses utf8mb3 but must be able to contain more than 63 characters. You cannot convert it to utf8mb4 unless you also change the data type to a longer type such as TEXT.
Similarly, a very long VARCHAR column may need to be changed to one of the longer TEXT types if you want to convert it from utf8mb3 to utf8mb4.

Additionally indexes vmay need to be changed as well to match the new sizes.

 I agree the old UT8mb3 should not be used anymore and it will be changed but not without some serious testing. There is also so much time. (And there are already too many emojis out there ;))

**Comment by viktorzen** [comment] 2019-12-20 20:50
looked into the mysql documentation and think the change from utf8mb3 to utf8mb4 is relatively straight-forward but needs testing of course. It's not such big of a deal in my opinion. If there are character and byte counting unicode bugs in the code they probably are already present in the current release, because characters can take up to 3 bytes already.

**Comment by acrylian** [comment] 2019-12-20 21:11
The change itself is relatively simple except the possible issue with fields mentioned above. 
Zenphoto itself should not have a problem with the encoding. This mb3/mb4 division is rather a MySQL speciality.
