### ISSUE TITLE
sitemap-extended creating album URLs with pages that do not exist

### ISSUE THREAD

**Issue by JesseHC** [zenphoto/zenphoto#1302] opened 2021-07-11 12:39 UTC
I noticed in 1.5.7 that when I created sitemaps using the sitemap-extended plugin it would create many extra URL entries for pages that did not exist in album sitemaps (such as- https://domain.com/zenphoto/demoalbum/page/2/). Google Search Console would start throwing lots of errors, and there was no easy way that I knew to fix it other than go through all the entries with extra pages in the album sitemaps and see if they were actually there, and if not, manually delete them.

After updating to 1.5.8 the issue is still there. I’ve been trying to troubleshoot it, since many of the pages only had a few images on them, and there was no way, even changing the settings, that there should be multiple pages.

I noticed tonight that all of the albums that were displaying the issue had subalbums in them. If they actually had multiple pages and a subablum, they would then add an extra page link. So for one with a “/page/2/“ and a subalbum, they would add a “/page/3/“ link to the album sitemap that did not exist.

Things I noticed, if there were multiple subablums, it still only creates one extra page that does not exist. It will also still create links for the subalbums, so I guess the only real issue is that you have a a bunch of broken links in your album sitemaps. It doesn’t create extra pages for _all_ albums with subalbums, only some of them. 

I think the only options I have enabled from the default in sitemap-extended are the Google ones:
- Enable Google image and video extension
- Google image and video extension: Link full image 
- Google - URL to image license

I’ve tried this both on my live server and test server, and both in 1.5.7 and 1.5.8.

Also, so you know, the “Info & download (GitHub)” link is broken at https://www.zenphoto.org/news/sitemap-extended/

Thanks!

**Comment by acrylian** [comment] 2021-07-11 12:49
Just to note current release is 1.5.9, although there were no changes to the sitemap plugin ;-)

We will have to try to reproduce that there are pages added that are not existing.

Thanks for the note about he Github link on the extensions page. That should not be there at all since it is an official plugin. That is fixed now.

**Comment by JesseHC** [comment] 2021-07-11 12:56
> Just to note current release is 1.5.9, although there were no changes to the sitemap plugin ;-)

Thanks! I didn't even notice that came out last week, though I had already applied one of the fixes manually. To be honest, I wrote this up weeks ago, but wanted to do some extra troubleshooting before I posted it.

**Comment by acrylian** [comment] 2021-07-11 13:16
I just checked the sitemap on zenphoto.org and I sadly cannot reproduce this. All albums have the pages they really have. Example:

![Bildschirmfoto 2021-07-11 um 15 11 56](https://user-images.githubusercontent.com/2474309/125196542-a6e6a700-e25a-11eb-8903-482ba7f372ed.jpg)

Exactly the six pages it actually has: https://www.zenphoto.org/theme/

Are you sure the wrong pages come from the sitemap itself and not the theme used so Google gets them from elsewhere? Themes need to be setup correctly so they block non existing pages as 404 not found pages correctly.

**Comment by JesseHC** [comment] 2021-07-11 13:37
It’s the album sitemaps themselves, because I had to go through all of them and manually check and delete all the wrong entries. Specifically the _sitemap-zenphoto-albums-(number).xml_ files.

I’m using a slightly modified version of Basic, so it should work. Some of the albums this is happening to have only 11 & 12 images in them. I even tried switching to just the Basic theme with the default settings, and the pages were not there.

**Comment by JesseHC** [comment] 2021-07-11 13:44
> Exactly the six pages it actually has: https://www.zenphoto.org/theme/

Does https://www.zenphoto.org/theme/ contain any subalbums? This was only happening to albums that contained them _(though not all)_.

**Comment by acrylian** [comment] 2021-07-11 13:46
Yes, https://www.zenphoto.org/theme/ contains lots of sub albums (as you can see if you visit the page).

Just in case you missed, you have to manually update the sitemap, it does not do that by itself (just in case you had just old entries because of that).

**Comment by acrylian** [comment] 2021-07-11 13:47
Do you use albums that have both sub album and images perhaps and is it perhaps happening to those specifially?

**Comment by JesseHC** [comment] 2021-07-11 14:05
I’ve been deleting and creating new sitemaps manually many times trying to test this.

I went back and checked some more and you’re right, it is only happening to albums that contain _both_ images _(or videos)_ and sub albums. If a folder only contains media or only folders, it will appear in the sitemaps without extra pages.

**Comment by acrylian** [comment] 2021-07-11 17:53
> it is only happening to albums that contain both images (or videos) and sub albums. 

Thanks, that's a clue to test with. I generally would recommend to use either sub albums or images wihtin albums as it seems to me best usability wise. Apparently here the sitemap does not take the "transition page" into account. Not to speak of the outdated concept of "columns" on the same theme option which will be removed anyway. I will look into this the next days.

**Comment by acrylian** [comment] 2021-07-12 15:50
I can confirm the issue. It is not only generating pages that don't exist, it also does not generate all pages that do if you have a shared subalbum/images album. One reason is that a function is theme context depentend which fails within the sitemap. No one noticed until your report.

This is a bit more complicated and will take some time. On that occasion I will also cleanup/remove the "theme columns" and rework a few things to be object dependent instead of context dependent.

**Closed** 2021-09-12 16:33 UTC
Labels: under investigation, work in progress
