### ISSUE TITLE
Image titles got lost while locale was out of date

### ISSUE THREAD

**Issue by tiltX** [zenphoto/zenphoto#903] opened 2015-02-23 23:01 UTC
I have made changes to an image's title text in the admin interface (/admin-edit.php?page=edit&album=[albumname]&tab=imageinfo) and after clicking the apply button, the image titles of ***all*** the images that were listed on the current page were blank.

I think I figured out what happened: saving titles to the database failed because the locale that was in use when the photo was uploaded (and when the title was written for the first time) wasn't availabe.

* I had upgraded to 1.4.7 but the German translation wasn't available. In the gallery's general options, German was listed with a yellow background (still at 1.4.6). The radiobutton, however, was still positioned next to "German".
* All text in the admin backend was in English though when I lost my image titles.
* I tried re-entering one of the deleted titles but it didn't work (it went back to blank after clicking the apply button).
* After manually downloading the German translation from github, I went to the general options again and made sure that German was available now (I had to switch to English, hit apply, then switch back to German because the newly uploaded po/mo files didn't register on their own).
* I went back to the image editing page and re-entered one of the deleted image titles.
* After clicking the apply button the title was no longer blank. Hurray!

This leads me to the conclusion that zenphoto might have tried to save image titles for de_DE but failed to do so due to the outdated locale files.

By the way, the multilingual option in my gallery is disabled but I might have enabled it in the past when I played around with zenphoto's capabilities.

**Comment by acrylian** [comment] 2015-02-24 09:09
I am sorry you lost content. That should of course not happen. We will have to try to reproduce this but that may take a while.

You are generally misunderstanding a bit how the translation stuff works:

The translation file must be present to be able to enable a language but it is not involved itself in content your enter manually and it is meaningless for this if the translation is current (btw German is current in 1.4.7 and just labeled wrong accidentally by me). The content your enter is stored in the database.

The language files are for the static texts – option descriptions, labels, menu etc. – on the backend only. If a translation is not current that only means that not all backend texts may be translated. You could even use an complete empty translation file to be able to enable a certain language.

**Comment by tiltX** [comment] 2015-02-25 13:58
I see. I thought the locale was involved in saving content as well, since I had the impression that zenphoto supports image descriptions and titles in multiple languages.

Anyway, the steps I've described are what happened. Ignore the conclusions I've drawn :-)

**Comment by acrylian** [comment] 2015-02-25 15:48
The locale is involved so that is enables the multilingual saving. Actually German used should be kept even if disabled and not get lost. I of course cannot exclude that there is a bug. In any case you can enable languages that are not marked as current.

**Comment by fretzl** [comment] 2015-03-01 13:52
Sorry but I cannot reproduce the issue.

**Comment by acrylian** [comment] 2015-03-01 15:36
A possibility would be that you upgraded from a much older version. There the strings were stored differently in single and multilingual mode. Then this probably could have happened if you had some older values.

**Comment by tiltX** [comment] 2015-03-01 20:24
I have upgraded from 1.4.5 to 1.4.6 and then to 1.4.7 in short succession (without saving any photo/album changes while in 1.4.6). The photos were potentially uploaded by an even older version than 1.4.5...

Thanks for looking into this, if you can't reproduce it it might have been a one-time weirdness. Like I said, I only lost 10 title strings... no biggie.

**Comment by acrylian** [comment] 2015-03-02 09:18
Ok, thanks. I will close the ticket for now. We can re-open it any time if necessary.

**Closed by acrylian** 2015-03-02 09:18 UTC
Labels: under investigation
